Repository hpcng/singularity, pull requests merged in 2018-09, with the labels that each got.

#1935 Add format arg to sylog errorf calls
  src/cmd/singularity/cli/build.go
  src/pkg/build/assemblers/assembler_sandbox.go
  src/pkg/build/sources/packer_ext3.go
  src/pkg/build/sources/packer_sandbox.go
  src/pkg/build/sources/packer_sif.go
  src/pkg/build/sources/packer_squashfs.go
  src/pkg/util/fs/files/group.go
Labels: Release 3.0

#1922 Developement 3.0: Display warning rather than returning an error for non existent sources
  src/pkg/util/fs/layout/layer/overlay/overlay.go
Labels: Release 3.0

#1950 Development 3.0: Always mount underlay final in RO
  src/pkg/util/fs/layout/layer/underlay/underlay.go
Labels: Release 3.0

#1921 Auto gen Bash completion file
  etc/bash_completion.d/bash_completion.go
  etc/bash_completion.d/singularity
  mlocal/frags/Makefile.stub
Labels: Release 3.0

#1920 Fix cleanenv
  src/cmd/singularity/cli/actions.go
  src/pkg/build/sources/base_environment.go
  src/pkg/util/env/clean.go
Labels: Release 3.0

#1957 Development 3.0: Restore user capabilities when joining instance
  src/runtime/engines/singularity/prepare.go
Labels: Release 3.0

#1956 add a missing build test for zypper bootstrapping
  src/cmd/singularity/build_test.go
Labels: Release 3.0

#1930 Library search
  src/cmd/singularity/cli/search.go
  src/docs/content.go
  src/pkg/library/client/api.go
  src/pkg/library/client/api_test.go
  src/pkg/library/client/models.go
  src/pkg/library/client/response.go
  src/pkg/library/client/search.go
  src/pkg/library/client/search_test.go
  src/pkg/library/client/util.go
Labels: Release 3.0

#1972 Set the HOME environment variable when setting different privileges during testing
  src/pkg/test/privilege.go
Labels: Release 3.0

#1964 OCI builder caching
  .travis.yml
  src/pkg/build/sources/conveyorPacker_oci.go
Labels: Release 3.0

#1978 Set SINGULARITY_CACHEDIR with the current UID
  .travis.yml
  src/pkg/test/privilege.go
Labels: Release 3.0

#1987 check if user is root before allowing build from definition
  src/pkg/build/build.go
Labels: Release 3.0

#1780 Yum ConveyorPacker
  src/pkg/build/build.go
  src/pkg/build/sources/conveyorPacker_yum.go
  src/pkg/build/sources/conveyorPacker_yum_test.go
  src/pkg/build/types/definition.go
Labels: Release 3.0

#1834 cleaning up some cruft left when we were trying to include dot versio…
  src/cmd/singularity/cli/capability_add.go
  src/cmd/singularity/cli/capability_drop.go
  src/cmd/singularity/cli/capability_list.go
  src/cmd/singularity/cli/instance_list.go
  src/cmd/singularity/cli/instance_start.go
  src/cmd/singularity/cli/instance_stop.go
  src/pkg/util/fs/mount/mount_test.go
Labels: Release 3.0

#1984 Development 3.0: fix instance hang while starting instance
  src/runtime/starter/smaster.go
Labels: Release 3.0

#1949 Development 3.0: Honor --allow-setuid flag
  src/runtime/engines/singularity/container.go
Labels: Release 3.0

#1918 Development 3.0: Fix overlay and some race condition
  src/pkg/build/sources/packer_ext3.go
  src/pkg/build/sources/packer_sif.go
  src/pkg/image/ext3.go
  src/pkg/image/image.go
  src/pkg/image/sandbox.go
  src/pkg/image/sif.go
  src/pkg/image/squashfs.go
  src/pkg/util/fs/layout/layer/overlay/overlay.go
  src/pkg/util/loop/loop.go
  src/runtime/engines/singularity/config.go
  src/runtime/engines/singularity/container.go
  src/runtime/engines/singularity/prepare.go
  src/runtime/engines/singularity/process.go
  src/runtime/engines/singularity/rpc/args.go
  src/runtime/engines/singularity/rpc/client/client.go
  src/runtime/engines/singularity/rpc/server/server.go
  src/runtime/starter/c/starter.c
Labels: Release 3.0

#1909 Build with Section and NoTest flags
  src/cmd/singularity/cli/build.go
  src/pkg/build/assemblers/assembler_sandbox.go
  src/pkg/build/assemblers/assembler_sif.go
  src/pkg/build/build.go
  src/pkg/build/sources/base_environment.go
  src/pkg/build/sources/conveyorPacker_oci.go
  src/pkg/build/types/bundle.go
  src/pkg/sylog/sylog.go
  src/runtime/engines/imgbuild/create.go
  src/runtime/engines/imgbuild/process.go
Labels: Release 3.0

#1981 help cmd | man <image>
  src/cmd/singularity/cli/keys_push.go
  src/cmd/singularity/cli/run_help.go
  src/cmd/singularity/cli/verify.go
  src/docs/content.go
Labels: Release 3.0

#1995 Remove flag "-vendor-only" dep ensure.
  Gopkg.lock
  mlocal/frags/Makefile.stub
Labels: Release 3.0

#1730 Development 3.0: selinux
  Gopkg.lock
  mlocal/checks/project.chk
  src/pkg/security/apparmor/apparmor_linux.go
  src/pkg/security/apparmor/apparmor_unsupported.go
  src/pkg/security/seccomp/seccomp_linux.go
  src/pkg/security/seccomp/seccomp_unsupported.go
  src/pkg/security/security.go
  src/pkg/security/selinux/selinux_linux.go
  src/pkg/security/selinux/selinux_unsupported.go
  src/runtime/engines/singularity/process.go
Labels: Release 3.0

#1993 Development 3.0: Fix instance stop
  src/cmd/singularity/cli/instance_stop.go
Labels: Release 3.0

#1998 Development 3.0: Reset MS_RDONLY flag in loops
  src/runtime/engines/singularity/container.go
Labels: Release 3.0

#1948 Development 3.0: Fix instance join
  src/runtime/engines/singularity/create.go
  src/runtime/engines/singularity/rpc/args.go
  src/runtime/engines/singularity/rpc/client/client.go
  src/runtime/engines/singularity/rpc/server/server.go
Labels: Release 3.0

#1960 Build update option
  src/cmd/singularity/cli/build.go
  src/pkg/build/assemblers/assembler_sandbox.go
  src/pkg/build/assemblers/assembler_sandbox_test.go
  src/pkg/build/assemblers/assembler_sif_test.go
  src/pkg/build/build.go
  src/pkg/build/conveyorPacker.go
  src/pkg/build/sources/base_environment.go
  src/pkg/build/sources/conveyorPacker_arch.go
  src/pkg/build/sources/conveyorPacker_arch_test.go
  src/pkg/build/sources/conveyorPacker_busybox.go
  src/pkg/build/sources/conveyorPacker_busybox_test.go
  src/pkg/build/sources/conveyorPacker_debootstrap.go
  src/pkg/build/sources/conveyorPacker_debootstrap_test.go
  src/pkg/build/sources/conveyorPacker_local.go
  src/pkg/build/sources/conveyorPacker_oci.go
  src/pkg/build/sources/conveyorPacker_oci_test.go
  src/pkg/build/sources/conveyorPacker_shub.go
  src/pkg/build/sources/conveyorPacker_shub_test.go
  src/pkg/build/sources/conveyorPacker_yum.go
  src/pkg/build/sources/conveyorPacker_yum_test.go
  src/pkg/build/types/bundle.go
  src/pkg/sylog/sylog.go
Labels: Release 3.0

#1671 Development 3.0: network support
  .travis.yml
  Gopkg.lock
  Gopkg.toml
  etc/network/00_bridge.conflist
  etc/network/10_ptp.conflist
  etc/network/20_ipvlan.conflist
  etc/network/30_macvlan.conflist
  mlocal/frags/Makefile.stub
  src/cmd/singularity/cli/action_flags.go
  src/cmd/singularity/cli/actions.go
  src/cmd/singularity/cli/instance_start.go
  src/pkg/network/network.go
  src/pkg/util/env/env.go
  src/pkg/util/priv/priv.go
  src/runtime/engines/singularity/cleanup.go
  src/runtime/engines/singularity/config.go
  src/runtime/engines/singularity/container.go
  src/runtime/engines/singularity/data/singularity.conf
  src/runtime/starter/c/starter.c
  src/runtime/starter/smaster.go
Labels: Release 3.0

#1932 3.0: Make rpm packaging work again
  dist/rpm/buildrpm
  dist/rpm/singularity.spec.in
  makeit/mconfig
  mlocal/checks/project.chk
  mlocal/frags/Makefile.stub
Labels: Release 3.0

#1729 Escape Docker/OCI ENV, CMD, ENTRYPOINT
  src/pkg/build/sources/conveyorPacker_oci.go
  src/pkg/util/shell/escape.go
  src/pkg/util/shell/escape_test.go
Labels: OCI, Release 3.0

#2029 Inspect command
  src/cmd/singularity/cli/inspect.go
  src/docs/content.go
  src/pkg/build/assemblers/assembler_sandbox.go
Labels: Release 3.0

#2037 updating URL in help to point to real docs
  src/docs/templates.go
Labels: Release 3.0

#2038 Toying with CircleCI
  .circleci/config.yml
Labels: WIP

#1927 Add special handling for /dev in userbinds
  src/runtime/engines/singularity/container.go
Labels: Release 3.0

#2036 Help with obtaining auth tokens in the PGP workflow
  src/cmd/singularity/cli/keys_push.go
  src/pkg/signing/signing.go
  src/pkg/sypgp/sypgp.go
Labels: Release 3.0

#2009 Development 3.0: Autofs bug path
  src/runtime/engines/singularity/config.go
  src/runtime/engines/singularity/prepare.go
  src/runtime/engines/singularity/process.go
Labels: Release 3.0

#2045 add runtime $PATH control via SINGULARITYENV_PATH / SINGULARITYENV_PREPEND_PATH / SINGULARITYENV_APPEND_PATH
  src/pkg/build/sources/base_environment.go
  src/pkg/util/env/clean.go
Labels: Release 3.0

#2004 Add singularity env tests
  src/cmd/singularity/env_test.go
Labels: Release 3.0

#2055 Library Conveyor Packer
  src/cmd/singularity/cli/actions.go
  src/cmd/singularity/cli/build.go
  src/pkg/build/build.go
  src/pkg/build/conveyorPacker.go
  src/pkg/build/sources/conveyorPacker_library.go
  src/pkg/build/sources/conveyorPacker_library_test.go
  src/pkg/libexec/pull.go
Labels: Release 3.0

#2066 Test cmd
  src/cmd/singularity/cli/actions.go
  src/docs/content.go
Labels: Release 3.0

#1986 Bind environment variables to CLI flags
  src/cmd/singularity/cli/action_flags.go
  src/cmd/singularity/cli/build.go
  src/cmd/singularity/cli/capability_add.go
  src/cmd/singularity/cli/capability_drop.go
  src/cmd/singularity/cli/capability_list.go
  src/cmd/singularity/cli/cli_test.go
  src/cmd/singularity/cli/inspect.go
  src/cmd/singularity/cli/instance_list.go
  src/cmd/singularity/cli/instance_stop.go
  src/cmd/singularity/cli/keys_list.go
  src/cmd/singularity/cli/keys_pull.go
  src/cmd/singularity/cli/keys_push.go
  src/cmd/singularity/cli/keys_search.go
  src/cmd/singularity/cli/pull.go
  src/cmd/singularity/cli/push.go
  src/cmd/singularity/cli/search.go
  src/cmd/singularity/cli/sign.go
  src/cmd/singularity/cli/singularity.go
  src/cmd/singularity/cli/verify.go
Labels: Release 3.0

#2061 merge CONTRIBUTORS.md in from 2.6.0
  CONTRIBUTORS.md
Labels: Release 3.0

#2060 sanitize path at beginning of code execution
  src/cmd/singularity/cli/singularity.go
Labels: Release 3.0

#2071 Use SIF version 1.0.0
  Gopkg.lock
  Gopkg.toml
Labels: Release 3.0

#2067 Remove redundant if-err checks
  src/cmd/singularity/cli/sign.go
  src/cmd/singularity/cli/verify.go
  src/cmd/singularity/import_export_test.go
  src/pkg/build/sources/packer_ext3.go
  src/pkg/instance/instance.go
  src/pkg/syecl/syecl_test.go
  src/pkg/util/fs/layout/layer/overlay/overlay.go
  src/pkg/util/fs/layout/layer/underlay/underlay.go
  src/pkg/util/fs/mount/mount.go
  src/pkg/util/priv/priv.go
  src/runtime/engines/singularity/rpc/server/server.go
Labels: Release 3.0, enhancement

#2028 Development 3.0: Add --security flag support
  Gopkg.lock
  etc/seccomp-profiles/default.json
  mlocal/frags/Makefile.stub
  src/cmd/singularity/cli/action_flags.go
  src/cmd/singularity/cli/actions.go
  src/cmd/singularity/cli/instance_start.go
  src/pkg/security/seccomp/seccomp_linux.go
  src/pkg/security/seccomp/seccomp_unsupported.go
  src/pkg/security/security.go
  src/runtime/engines/singularity/config.go
  src/runtime/engines/singularity/prepare.go
Labels: Release 3.0

#2078 Sign and verify optional SIF IDs and Groups
  Gopkg.lock
  Gopkg.toml
  src/cmd/singularity/cli/sign.go
  src/cmd/singularity/cli/verify.go
  src/pkg/signing/signing.go
Labels: Release 3.0

#2040 Development 3.0: Add cgroups support
  Gopkg.lock
  Gopkg.toml
  mlocal/frags/Makefile.stub
  src/cmd/singularity/cli/action_flags.go
  src/cmd/singularity/cli/actions.go
  src/pkg/cgroups/cgroups.go
  src/pkg/cgroups/cgroups_test.go
  src/pkg/cgroups/config.go
  src/pkg/cgroups/example/cgroups.toml
  src/runtime/engines/singularity/cleanup.go
  src/runtime/engines/singularity/config.go
  src/runtime/engines/singularity/container.go
Labels: Release 3.0

#1971 Support old images without /.singularity.d/actions/exec
  src/runtime/engines/singularity/process.go
Labels: Release 3.0

#2082 Remove skip now that all tests are passing
  src/cmd/singularity/env_test.go
Labels: Release 3.0

#2090 Development 3.0: instances fixes
  src/runtime/engines/singularity/create.go
  src/runtime/engines/singularity/rpc/args.go
  src/runtime/engines/singularity/rpc/client/client.go
  src/runtime/engines/singularity/rpc/server/server.go
Labels: Release 3.0

#2093 Development 3.0: Apply missing MS_NODEV mount flag with overlay
  src/pkg/util/fs/layout/layer/overlay/overlay.go
Labels: Release 3.0

#2094 Development 3.0: fix net namespace description and add CNI configuration directives
  src/cmd/singularity/cli/action_flags.go
  src/runtime/engines/singularity/data/singularity.conf
Labels: Release 3.0

#2081 Add instance tests
  src/cmd/singularity/instance_test.go
Labels: Release 3.0

#2117 Development 3.0: Allow /dev bind with --contain
  src/runtime/engines/singularity/container.go
Labels: Release 3.0

#2128 Fix instances test
  src/cmd/singularity/build_test.go
  src/cmd/singularity/instance_test.go
Labels: Release 3.0, Testing, bug

#2130 Fix typos
  src/cmd/singularity/cli/inspect.go
  src/docs/content.go
  src/pkg/build/build.go
  src/pkg/build/builder_remote_test.go
  src/pkg/build/types/parser/deffile.go
  src/pkg/syecl/syecl_test.go
  src/pkg/util/capabilities/file.go
  src/runtime/engines/singularity/container.go
  src/runtime/engines/singularity/rpc/server/server.go
Labels: enhancement, scaryness

#2112 Address apps comments from previous PR
  src/pkg/syplugin/build.go
  src/plugins/apps/apps.go
Labels: tech debt

#2114 Update Library pull tests
  examples/library/Singularity
  src/cmd/singularity/build_test.go
  src/cmd/singularity/pull_test.go
Labels: Release 3.0, Testing

#2132 nvidia-contiainer-cli fix
  src/pkg/util/nvidiautils/nvidiautils.go
Labels: bug

#2096 Development 3.0: Honor max loop devices configuration directive
  src/pkg/build/sources/packer_ext3.go
  src/pkg/build/sources/packer_sif.go
  src/pkg/util/loop/loop.go
  src/runtime/engines/singularity/rpc/server/server.go
Labels: Release 3.0

#2139 Development 3.0: Ignore unknown GID
  src/runtime/engines/singularity/prepare.go
Labels: Release 3.0

#2106 Makefile: fix CNI configuration file permission
  mlocal/frags/Makefile.stub
Labels: Release 3.0, enhancement

#2100 Development 3.0: Provide debug output for instance and information status
  src/cmd/singularity/cli/actions.go
  src/pkg/instance/instance.go
  src/pkg/util/exec/pipe.go
Labels: Release 3.0
