Repository hpcng/singularity, pull requests merged in 2018-06, with the labels that each got.

#1633 Fix Library Image Download Perms
  src/pkg/library/client/pull.go
Labels: Release 3.0, bug

#1639 Clarify Engine and Configuration naming conventions - WIP
  src/cmd/singularity/cli/action_flags.go
  src/cmd/singularity/cli/actions.go
  src/cmd/singularity/cli/build.go
  src/pkg/sylog/sylog.go
  src/pkg/workflows/config/config.go
  src/pkg/workflows/workflows.go
  src/runtime/engines/common/config/config.go
  src/runtime/engines/common/config/parser.go
  src/runtime/engines/common/oci/command.go
  src/runtime/engines/common/oci/config/annotations.go
  src/runtime/engines/common/oci/config/config.go
  src/runtime/engines/common/oci/config/config_linux.go
  src/runtime/engines/common/oci/config/config_solaris.go
  src/runtime/engines/common/oci/config/config_windows.go
  src/runtime/engines/common/oci/config/default_linux.go
  src/runtime/engines/common/oci/config/hooks.go
  src/runtime/engines/common/oci/config/hostname.go
  src/runtime/engines/common/oci/config/linux.go
  src/runtime/engines/common/oci/config/mounts.go
  src/runtime/engines/common/oci/config/process.go
  src/runtime/engines/common/oci/config/process_linux.go
  src/runtime/engines/common/oci/config/process_solaris.go
  src/runtime/engines/common/oci/config/root.go
  src/runtime/engines/common/oci/config/solaris.go
  src/runtime/engines/common/oci/config/version.go
  src/runtime/engines/common/oci/config/windows.go
  src/runtime/engines/engines.go
  src/runtime/engines/singularity/check.go
  src/runtime/engines/singularity/cleanup.go
  src/runtime/engines/singularity/config.go
  src/runtime/engines/singularity/create.go
  src/runtime/engines/singularity/data/singularity.conf
  src/runtime/engines/singularity/engine.go
  src/runtime/engines/singularity/monitor.go
  src/runtime/engines/singularity/process.go
  src/runtime/engines/singularity/rpc/args.go
  src/runtime/engines/singularity/rpc/client/client.go
  src/runtime/engines/singularity/rpc/server/server.go
  src/runtime/startup/c/wrapper.h
  src/runtime/startup/rpc.go
  src/runtime/startup/scontainer.go
  src/runtime/startup/smaster.go
  src/runtime/workflows/rpc/server.go
  src/runtime/workflows/workflows.go
  src/runtime/workflows/workflows/singularity/config/config.go
  src/runtime/workflows/workflows/singularity/runtime.go
Labels: WIP

#1663 Support additional docker and oci build sources
  Gopkg.lock
  Gopkg.toml
  src/cmd/singularity/cli/build.go
  src/pkg/build/assembler_sif_test.go
  src/pkg/build/conveyorPacker.go
  src/pkg/build/conveyorPacker_docker.go
  src/pkg/build/conveyorPacker_docker_test.go
  src/pkg/build/conveyorPacker_oci.go
  src/pkg/build/conveyorPacker_oci_test.go
  src/pkg/build/definition.go
Labels: OCI, Release 3.0
