Repository hpcng/singularity, pull requests merged in 2018-10, with the labels that each got.

#2119 Port 2.x 30-actions.sh to 3.0
  src/cmd/singularity/actions_test.go
  src/cmd/singularity/build_test.go
  src/cmd/singularity/docker_test.go
  src/cmd/singularity/exec_test.go
Labels: Release 3.0, Testing

#2151 Fix config parser handling of string fields
  src/runtime/engines/config/parser.go
Labels: bug

#2140 Development 3.0: Rewrite target UID/GID
  src/cmd/singularity/cli/actions.go
  src/pkg/util/fs/files/files_linux_test.go
  src/pkg/util/fs/files/group.go
  src/pkg/util/fs/files/passwd.go
  src/runtime/engines/config/starter/starter.go
  src/runtime/engines/singularity/config.go
  src/runtime/engines/singularity/container.go
  src/runtime/engines/singularity/prepare.go
  src/runtime/engines/singularity/process.go
  src/runtime/starter/c/starter.c
  src/runtime/starter/c/starter.h
  src/runtime/starter/rpc.go
  src/runtime/starter/smaster.go
Labels: Release 3.0

#2113 Development 3.0: Fix resolv.conf not mounted with network namespace
  src/runtime/engines/singularity/container.go
Labels: Release 3.0

#2154 Remove Image cmd test cases
  src/cmd/singularity/build_test.go
  src/cmd/singularity/help_test.go
  src/cmd/singularity/import_export_test.go
Labels: Hacktoberfest, Release 3.0, Testing

#2157 Admin Set Mksquashfs Path
  src/pkg/build/assemblers/assembler_sif.go
  src/runtime/engines/singularity/config.go
  src/runtime/engines/singularity/data/singularity.conf
Labels: Release 3.0

#2025 Fix travis on personal github repositories
  .travis.yml
Labels: Testing, enhancement

#2155 Test porting 2.x->3.0 Test (31-action_uris.sh)
  src/cmd/singularity/actions_test.go
  src/cmd/singularity/build_test.go
  src/cmd/singularity/docker_test.go
Labels: Hacktoberfest, Release 3.0, Testing

#2177 Development 3.0: Add missing CLI options environment variables
  src/cmd/singularity/cli/action_flags.go
  src/cmd/singularity/cli/singularity.go
Labels: Release 3.0, bug

#2179 Fix bug introduced by PR #2155
  src/cmd/singularity/actions_test.go
Labels: Hacktoberfest, Release 3.0, Testing, bug

#2141 Update README.md
  CONTRIBUTORS.md
  README.md
Labels: Documentation, Hacktoberfest, enhancement

#2180 Test porting
  src/cmd/singularity/actions_test.go
Labels: Hacktoberfest, Release 3.0, Testing, bug, enhancement

#2160 Development 3.0: Resolve symlinks during mount operation
  src/runtime/engines/singularity/container.go
Labels: Release 3.0, bug

#2162 Add warning if more than 50 bind mounts required for underlay
  src/pkg/util/fs/layout/layer/underlay/underlay.go
Labels: Hacktoberfest, Release 3.0

#2048 3.0: Fix rpm build after introduction of cni
  dist/rpm/singularity.spec.in
  mlocal/frags/Makefile.stub
Labels: Release 3.0, enhancement

#2161 Clean build environment
  src/runtime/engines/imgbuild/process.go
Labels: Release 3.0

#2184 Addition of config profile, overall cleanup to the Makeit build system
  makeit/genmod.awk
  makeit/mconfig
  mlocal/checks/basechecks.chk
  mlocal/checks/project.chk
  mlocal/frags/Makefile.stub
  mlocal/frags/common_opts.mk
  mlocal/frags/go_appsec_opts.mk
  mlocal/frags/go_common_opts.mk
  mlocal/frags/go_normal_opts.mk
  mlocal/frags/go_stripped_opts.mk
Labels: Release 3.0, WIP

#2187 Travis tests
  src/cmd/singularity/actions_test.go
  src/cmd/singularity/testdata/runscript.sh
Labels: Testing, bug

#2185 Makeit: Allow configurable build/install paths.
  mlocal/checks/project.chk
  mlocal/frags/Makefile.stub
  mlocal/frags/go_appsec_opts.mk
  mlocal/frags/go_common_opts.mk
  mlocal/frags/paths.stub
Labels: Release 3.0, enhancement

#2181 Development 3.0: Abort when mount error occurs for filesystems
  src/runtime/engines/singularity/container.go
Labels: Release 3.0, bug

#2186 Development 3.0: Add selinux and seccomp dep constraint
  Gopkg.toml
Labels: Release 3.0

#2188 Bind mount action scripts in runtime
  etc/actions/exec
  etc/actions/run
  etc/actions/shell
  etc/actions/start
  etc/actions/test
  mlocal/frags/Makefile.stub
  src/runtime/engines/singularity/container.go
Labels: Hacktoberfest, Release 3.0

#2191 list actions files instead of using wildcard
  mlocal/frags/Makefile.stub
Labels: Release 3.0, enhancement

#2190 Development 3.0: Fix app environment variable
  src/cmd/singularity/cli/action_flags.go
Labels: Release 3.0, bug

#2110 Chown images after build with sudo
  src/pkg/build/assemblers/assembler_sif.go
Labels: Release 3.0, WIP, bug

#2192 Build Service JSON Response Format
  src/pkg/build/builder_remote.go
  src/pkg/build/builder_remote_test.go
  src/pkg/jsonresp/json_response.go
  src/pkg/jsonresp/json_response_test.go
Labels: Release 3.0

#2195 Fix URIs
  src/docs/content.go
  src/pkg/build/builder_remote.go
  src/pkg/build/sources/conveyorPacker_library_test.go
Labels: Documentation, Release 3.0, bug

#2198 Development 3.0: Allow to specify all with --add/drop-caps
  etc/capabilities/user.root
  src/pkg/util/capabilities/capabilities.go
Labels: Release 3.0, enhancement

#2153 Tidy up repo documentation before v3.0.0 release
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  CONTRIBUTING.md
  CONTRIBUTORS.md
  INSTALL.md
  README.md
Labels: Documentation, WIP

#2183 Tidy up help docs
  src/cmd/singularity/actions_test.go
  src/cmd/singularity/build_test.go
  src/cmd/singularity/cli/action_flags.go
  src/cmd/singularity/cli/build.go
  src/cmd/singularity/cli/capability_add.go
  src/cmd/singularity/cli/capability_drop.go
  src/cmd/singularity/cli/capability_list.go
  src/cmd/singularity/cli/inspect.go
  src/cmd/singularity/cli/instance_stop.go
  src/cmd/singularity/cli/pull.go
  src/cmd/singularity/cli/push.go
  src/cmd/singularity/cli/singularity.go
  src/cmd/singularity/instance_test.go
  src/docs/content.go
Labels: Documentation, Release 3.0, enhancement

#2193 Fix rootless --remote from deffile
  src/cmd/singularity/cli/build.go
  src/pkg/build/build.go
Labels: Hacktoberfest, Release 3.0, bug

#2156 Development 3.0: Nvidia stuff rewrite and fix --nv with --writable
  etc/nvliblist.conf
  src/cmd/singularity/cli/action_flags.go
  src/cmd/singularity/cli/actions.go
  src/cmd/singularity/cli/instance_start.go
  src/cmd/singularity/cli/singularity.go
  src/pkg/util/nvidiautils/nvidiautils.go
  src/runtime/engines/singularity/config.go
  src/runtime/engines/singularity/container.go
Labels: Release 3.0, bug

#2204 Release procedure updates
  .github/RELEASE_CHECKLIST.md
  .github/RELEASE_PROCEDURE.md
  makeit/mconfig
Labels: Documentation, bug

#2199 Development 3.0: Instance log chown fix. Enable no new privileges with --no-privs
  src/pkg/instance/instance.go
  src/runtime/engines/singularity/prepare.go
Labels: Release 3.0, bug, enhancement

#2219 Update missing dependencies on INSTALL.md
  INSTALL.md
Labels: Documentation, Hacktoberfest, enhancement

#2218 Add --name flag to pull cmd
  src/cmd/singularity/cli/pull.go
  src/cmd/singularity/cli/singularity.go
Labels: Documentation, Hacktoberfest, behavior change, bug

#2229 Fix fatal error 'while trying to size SIF file to mmap'
  src/pkg/signing/signing.go
Labels: Release 3.0, bug

#2231 Don't reset root capabilities while using seccomp
  src/pkg/security/seccomp/seccomp_linux.go
Labels: Release 3.0, bug

#2202 Add travis checks for centos 6 and 7 rpms
  .travis.yml
  .travis/before_install
  .travis/build_test
  .travis/centos_run
  .travis/docker_run
  .travis/install_test
  .travis/rpmbuild_test
  .travis/script
  dist/rpm/singularity.spec.in
  mlocal/frags/Makefile.stub
  mlocal/frags/go_normal_opts.mk
Labels: Hacktoberfest, Testing, enhancement

#2226 Fix RPM building with buildrpm script
  dist/rpm/singularity.spec.in
  makeit/mconfig
  mlocal/frags/Makefile.stub
  mlocal/frags/common_opts.mk
Labels: Hacktoberfest, bug

#2175 Allow colon in image names
  src/cmd/singularity/cli/actions.go
  src/pkg/build/build.go
  src/pkg/build/conveyorPacker.go
  src/pkg/util/uri/uri.go
  src/pkg/util/uri/uri_test.go
Labels: Hacktoberfest, enhancement

#2235 Correct the default package version number
  makeit/mconfig
Labels: Hacktoberfest, Release 3.1.0, bug

#2236 Add a make rpm target
  INSTALL.md
  mlocal/frags/Makefile.stub
Labels: Hacktoberfest, Release 3.1.0

#2237 Makeit is platform independent again.
  makeit/gengodep
  makeit/mconfig
  mconfig
  mlocal/checks/basechecks.chk
  mlocal/frags/Makefile.stub
Labels: Release 3.1.0, enhancement

#2241 Fix filesystem UID for RPC server
  src/runtime/starter/c/starter.c
Labels: Release 3.0, bug

#2239 Fix ext3 image detection
  src/pkg/image/ext3.go
  src/pkg/image/image.go
Labels: Release 3.0, bug

#2247 Fix support for old image action layout
  src/runtime/engines/singularity/container.go
Labels: Release 3.0, bug

#2246 Fix USER_PATH by appending default singularity PATH
  src/cmd/singularity/cli/singularity.go
Labels: Release 3.0, bug

#2258 Yum updateurl fix
  src/pkg/build/types/parser/deffile.go
Labels: Image Building, Release 3.1.0, bug

#2266 Overlay fixes
  src/pkg/util/fs/helper.go
  src/pkg/util/fs/helper_linux_test.go
  src/pkg/util/fs/layout/layer/overlay/overlay.go
  src/runtime/engines/singularity/container.go
Labels: Release 3.0, bug

#2270 Remove 'allow user/root capabilities' directives
  etc/conf/testdata/test_1.out.correct
  etc/conf/testdata/test_2.out.correct
  etc/conf/testdata/test_3.in
  etc/conf/testdata/test_3.out.correct
  etc/conf/testdata/test_default.tmpl
  src/runtime/engines/singularity/config.go
  src/runtime/engines/singularity/data/singularity.conf
  src/runtime/engines/singularity/prepare.go
Labels: Release 3.0

#2271 Rewrite starter log message
  src/runtime/c/lib/util/message.c
  src/runtime/c/lib/util/message.h
  src/runtime/starter/c/starter.c
Labels: Release 3.0, enhancement

#2309 Add MS_MOVE chroot method and fallback to it if pivot_root failed
  src/runtime/engines/imgbuild/create.go
  src/runtime/engines/singularity/container.go
  src/runtime/engines/singularity/rpc/args.go
  src/runtime/engines/singularity/rpc/client/client.go
  src/runtime/engines/singularity/rpc/server/server.go
Labels: Release 3.0, enhancement

#2313 Improved mksquashfs error output in SIF Assembler
  src/pkg/build/assemblers/assembler_sif.go
Labels: enhancement

#2310 Fix filesystem UID
  src/runtime/starter/c/starter.c
Labels: Release 3.0, bug

#2288 User capabilities and starter.c build fixes
  mlocal/checks/project.chk
  mlocal/frags/Makefile.stub
Labels: Release 3.0, bug

#2330 Set container processs as terminal foreground process
  src/runtime/starter/c/starter.c
  src/runtime/starter/smaster.go
Labels: bug
