Repository hpcng/singularity, pull requests merged in 2018-11, with the labels that each got.

#2342 Starter refactoring
  cmd/starter/main.go
  internal/app/starter/master.go
  internal/app/starter/rpc.go
  internal/app/starter/stage.go
  makeit/gengodep
  mlocal/frags/Makefile.stub
Labels: Release 3.1.0, tech debt

#2150 fix image expand behavior, issue #1076
  CHANGELOG.md
  CONTRIBUTORS.md
  libexec/cli/image.expand.exec
Labels: Hacktoberfest

#2355 Move internal/pkg/jsonresp -> pkg/jsonresp
  internal/pkg/build/remotebuilder/remotebuilder.go
  internal/pkg/build/remotebuilder/remotebuilder_test.go
  pkg/jsonresp/json_response.go
  pkg/jsonresp/json_response_test.go
Labels: Release 3.1.0, tech debt

#2358 Fix logic while creating loop devices
  internal/pkg/runtime/engines/singularity/rpc/server/server.go
  internal/pkg/util/loop/loop.go
Labels: Release 3.1.0, bug

#2366 Fix terminal issues and signal handling
  cmd/starter/c/starter.c
  internal/app/starter/master.go
  internal/pkg/runtime/engines/imgbuild/process.go
  internal/pkg/runtime/engines/singularity/monitor.go
Labels: Release 3.1.0, bug

#2382 Use same umask as v2
  cmd/singularity/cli/actions.go
  internal/pkg/build/build.go
Labels: Release 3.1.0, bug

#2368 Change to preferred capitialization for Slurm.
  docs/2.x-slurm/README.md
  docs/2.x-slurm/singularity.c
Labels: Documentation

#2388 Add minimal tests for --app
  CONTRIBUTORS.md
  cmd/singularity/actions_test.go
  examples/busybox/Singularity
Labels: Testing

#2396 Use SINGULARITY_TMPDIR for builds
  cmd/singularity/cli/action_flags.go
  cmd/singularity/cli/actions.go
  cmd/singularity/cli/build.go
  cmd/singularity/cli/build_linux.go
  cmd/singularity/cli/pull.go
  cmd/singularity/cli/pull_linux.go
  cmd/singularity/cli/singularity.go
  internal/pkg/build/assemblers/assembler_sandbox_test.go
  internal/pkg/build/assemblers/assembler_sif_test.go
  internal/pkg/build/build.go
  internal/pkg/build/sources/conveyorPacker_arch_test.go
  internal/pkg/build/sources/conveyorPacker_busybox_test.go
  internal/pkg/build/sources/conveyorPacker_debootstrap_test.go
  internal/pkg/build/sources/conveyorPacker_library_test.go
  internal/pkg/build/sources/conveyorPacker_oci_test.go
  internal/pkg/build/sources/conveyorPacker_shub_test.go
  internal/pkg/build/sources/conveyorPacker_yum_test.go
  internal/pkg/build/types/bundle.go
  internal/pkg/libexec/pull.go
Labels: Image Building, behavior change

#2395 Issue 2166
  cmd/singularity/actions_test.go
Labels: Testing

#2359 Explicitily initialize engines and don't rely on Go init()
  cmd/singularity/cli/actions.go
  cmd/starter/main.go
  etc/conf/gen.go
  internal/pkg/runtime/engines/config/parser.go
  internal/pkg/runtime/engines/engines.go
  internal/pkg/runtime/engines/singularity/config.go
  internal/pkg/runtime/engines/singularity/container.go
  internal/pkg/runtime/engines/singularity/create.go
  internal/pkg/runtime/engines/singularity/prepare.go
  internal/pkg/runtime/engines/singularity/rpc/args.go
  internal/pkg/runtime/engines/singularity/rpc/client/client.go
  internal/pkg/runtime/engines/singularity/rpc/server/server.go
Labels: Release 3.1.0, bug

#2360 Fix push when using another PGP keyserver
  pkg/sypgp/sypgp.go
Labels: Release 3.1.0, bug

#2372 Fix symlink resolution for SESSIONDIR
  internal/pkg/runtime/engines/imgbuild/create.go
  internal/pkg/runtime/engines/singularity/container.go
Labels: Release 3.1.0, bug

#2393 Fix stat issue (while trying to size SIF file to mmap)
  cmd/starter/c/starter.c
Labels: Release 3.1.0, bug

#2375 singularity-2.6.0 and singularity-3.0.1
  dist/alpinelinux/singularity-2.6.0/APKBUILD
  dist/alpinelinux/singularity-3.0.1/APKBUILD
Labels: packaging

#2400 Fix network namespace usage for users
  internal/pkg/network/network.go
  internal/pkg/runtime/engines/singularity/container.go
Labels: Release 3.1.0, behavior change

#2408 Enhance test suite for scif apps feature
  cmd/singularity/actions_test.go
Labels: Testing, enhancement
