Repository hpcng/singularity, pull requests merged in 2018-12, with the labels that each got.

#2422 Check ID mapping
  internal/pkg/runtime/engines/config/starter/starter.go
  internal/pkg/runtime/engines/singularity/prepare.go
Labels: bug

#2416 More thorough instance tests
  cmd/singularity/instance_test.go
  examples/instances/Singularity
Labels: Testing, enhancement

#2437 Silence progress bars when appropriate flag set.
  pkg/client/library/pull.go
  pkg/client/library/push.go
  pkg/client/net/pull.go
  pkg/client/shub/pull.go
Labels: bug

#2436 Print multiple environments from inspect if they exist.
  cmd/singularity/cli/inspect.go
Labels: behavior change, enhancement

#2459 Overlay test
  .travis/rpmbuild_test
  cmd/singularity/actions_test.go
Labels: Testing
