Repository hpcng/singularity, pull requests merged in 2018-04, with the labels that each got.

#1448 b.build() returns err
  internal/pkg/cli/build.go
  pkg/build/builder.go
  pkg/build/builder_legacy.go
  pkg/build/builder_sif.go
Labels: Release 3.0, enhancement

#1463 Correct ENTRYPOINT + CMD behaviour - 3.0
  pkg/build/provisioner_docker.go
Labels: OCI, Release 3.0

#1462 Constrain docker_provision Untar to provided dst folder (3.0)
  pkg/build/provisioner_docker.go
Labels: Release 3.0
