Repository hpcng/singularity, pull requests merged in 2019-01, with the labels that each got.

#2498 Add Go version check. And speed test failure with new -failfast option
  cmd/singularity/cli.go
  cmd/starter/main.go
  internal/pkg/util/goversion/goversion.go
  internal/pkg/util/goversion/goversion_unsupported.go
  mlocal/frags/Makefile.stub
Labels: Release 3.1.0, enhancement

#2478 Fix fedora & epel builds for some architectures
  dist/rpm/singularity.spec.in
  internal/pkg/runtime/engines/singularity/process.go
  mlocal/checks/basechecks.chk
Labels: packaging

#2512 Exit instance when receiving signals and there is no more container processes
  docs/content.go
  etc/actions/start
  internal/app/singularity/instance_start.go
  internal/pkg/instance/instance.go
  internal/pkg/runtime/engines/singularity/process.go
Labels: Release 3.1.0

#2539 Add "--app" flag to run-help command
  internal/app/singularity/run_help.go
Labels: Release 3.1.0

#2510 Child images inherit parent environment
  internal/pkg/build/build.go
Labels: Release 3.1.0

#2533 Check ownership of config file
  cmd/singularity/cli_test.go
  cmd/singularity/security_test.go
  etc/conf/gen_test.go
  internal/pkg/runtime/engines/config/parser.go
  internal/pkg/syecl/syecl.go
  pkg/util/capabilities/file.go
Labels: Testing, regression

#2552 Get rid of eval for exec in runscript
  internal/pkg/build/sources/conveyorPacker_oci.go
Labels: Release 3.1.0

#2558 Fix check for conf file ownership
  internal/app/singularity/actions.go
  internal/pkg/runtime/engines/config/parser.go
  internal/pkg/runtime/engines/singularity/config.go
  internal/pkg/runtime/engines/singularity/prepare.go
  internal/pkg/syecl/syecl.go
  pkg/util/capabilities/file.go
Labels: Security fix, behavior change, bug

#2564 Add tests for pkg/util/fs/lock package
  pkg/util/fs/lock/lock_test.go
Labels: Release 3.1.0, Testing

#2565 Add tests for pkg/util/loop package
  pkg/util/loop/loop.go
  pkg/util/loop/loop_linux_test.go
Labels: Release 3.1.0, Testing

#2563 Add tests for pkg/util/copy package
  internal/pkg/runtime/engines/oci/process.go
  pkg/util/copy/buffer.go
  pkg/util/copy/buffer_test.go
  pkg/util/copy/writer.go
  pkg/util/copy/writer_test.go
Labels: Release 3.1.0, Testing

#2581 Remove `wget` as a build requirement for the RPM.
  dist/rpm/singularity.spec.in
Labels: packaging

#2551 Library Caching for Pulls and Builds
  internal/app/singularity/pull_linux.go
  internal/pkg/build/sources/conveyorPacker_library.go
Labels: Release 3.1.0

#2577 Fix client image pull race
  internal/app/starter/master.go
  pkg/client/library/pull.go
Labels: Release 3.1.0, bug

#2574 Add tests for pkg/util/unix package
  pkg/util/unix/socket_test.go
Labels: Release 3.1.0, Testing

#2593 Update README.md
  README.md
Labels: Documentation

#2607 Fix GC issue for lock package
  pkg/util/fs/lock/lock.go
Labels: Release 3.1.0, bug

#2609 Use open syscall to hold container network namespace reference
  internal/pkg/runtime/engines/singularity/container.go
Labels: Release 3.1.0, bug

#2610 Fix potential GC close issue
  internal/pkg/runtime/engines/oci/prepare.go
  internal/pkg/runtime/engines/oci/process.go
  internal/pkg/util/exec/pipe_linux.go
Labels: Release 3.1.0, bug

#2626 Update INSTALL.md
  INSTALL.md
Labels: Documentation

#2042 Zypper conveyorPacker
  examples/opensuse/Singularity
  internal/pkg/build/build.go
  internal/pkg/build/sources/conveyorPacker_zypper.go
  internal/pkg/build/sources/conveyorPacker_zypper_test.go
Labels: Image Building, Release 3.1.0
