Repository hpcng/singularity, pull requests merged in 2019-10, with the labels that each got.

#4540 Fallback correctly to user namespace for non setuid installation
  cmd/internal/cli/actions_linux.go
Labels: Bug, Regression

#4495 Rethink plugin system
  .golangci.yml
  cmd/internal/cli/action_flags.go
  cmd/internal/cli/actions_linux.go
  cmd/internal/cli/plugin_compile_linux.go
  cmd/internal/cli/plugin_disable_linux.go
  cmd/internal/cli/plugin_enable_linux.go
  cmd/internal/cli/plugin_inspect_linux.go
  cmd/internal/cli/plugin_install_linux.go
  cmd/internal/cli/plugin_linux.go
  cmd/internal/cli/plugin_list_linux.go
  cmd/internal/cli/plugin_uninstall_linux.go
  cmd/internal/cli/singularity.go
  examples/plugins/cli-plugin/README.md
  examples/plugins/cli-plugin/main.go
  examples/plugins/config-plugin/main_linux.go
  examples/plugins/test-plugin/main.go
  internal/app/singularity/plugin_compile_linux.go
  internal/app/singularity/plugin_list_linux.go
  internal/pkg/plugin/binary.go
  internal/pkg/plugin/command.go
  internal/pkg/plugin/flag.go
  internal/pkg/plugin/load.go
  internal/pkg/plugin/registry.go
  pkg/cmdline/cmd.go
  pkg/plugin/command.go
  pkg/plugin/flag.go
  pkg/plugin/manifest.go
  pkg/plugin/plugin.go
  pkg/plugin/register.go
Labels: BehaviorChange, Plugin

#4566 Cherry pick #4434 and #4436 into release-3.4 for 3.4.2
  mlocal/frags/build_runtime_suid.mk
Labels: Release 3.4

#4542 Honor the umask when building a SIF
  internal/pkg/build/build.go
Labels: Bug

#4549 Fix race condition with shared loop device
  pkg/util/loop/loop_linux.go
Labels: Bug, Release 3.5

#4570 Debug the version of Singularity when running a command
  cmd/internal/cli/singularity.go
Labels: Enhancement

#4564 Remove plugin manifest generator
  cmd/plugin_manifestgen/main.go
  internal/app/singularity/plugin_compile_linux.go
Labels: Enhancement, Plugin

#4554 Add e2e build tests for fakeroot
  e2e/docker/docker.go
  e2e/imgbuild/imgbuild.go
  e2e/internal/e2e/imageverify.go
  e2e/regressions/build.go
Labels: Testing, e2e

#4565 Split internal plugin code into multiple files
  internal/pkg/plugin/binary.go
  internal/pkg/plugin/load.go
  internal/pkg/plugin/meta.go
  internal/pkg/plugin/registry.go
  internal/pkg/plugin/sif.go
  internal/pkg/plugin/sif_test.go
Labels: Plugin, TechnicalDebt

#4423 Support for 'inspect' to handle label a partition
  cmd/internal/cli/inspect.go
  cmd/internal/cli/inspect_darwin.go
  cmd/internal/cli/inspect_linux.go
  e2e/inspect/inspect.go
  e2e/internal/e2e/imageverify.go
  e2e/testdata/inspecter_container.sif
Labels: Enhancement

#4611 Correctly handle group id when signing a group
  e2e/sign/sign.go
  e2e/verify/verify.go
  pkg/signing/signing.go
Labels: Bug

#4589 Fix current working directory mount check
  e2e/actions/actions.go
  e2e/actions/regressions.go
  e2e/internal/e2e/singularitycmd.go
  internal/pkg/runtime/engine/singularity/container_linux.go
  internal/pkg/runtime/engine/singularity/rpc/args.go
  internal/pkg/runtime/engine/singularity/rpc/client/client.go
  internal/pkg/runtime/engine/singularity/rpc/server/server_linux.go
Labels: Bug, Regression, Release 3.5

#4601 Error if '--sif-id' is 0
  cmd/internal/cli/sign.go
  cmd/internal/cli/verify.go
Labels: CLI, Enhancement

#4551 Allow large user mapping range with fakeroot
  internal/pkg/fakeroot/fakeroot.go
  internal/pkg/fakeroot/fakeroot_test.go
Labels: Enhancement, Release 3.5, Runtime

#4603 Fix overlay ext3 mount failure with ESTALE
  internal/pkg/runtime/engine/singularity/container_linux.go
Labels: Bug, Release 3.5

#4618 Fix exit code for e2e sign tests
  e2e/sign/sign.go
Labels: Bug, e2e

#4614 Rework singularity configuration parser
  cmd/internal/cli/actions_linux.go
  etc/conf/gen.go
  etc/conf/singularity.conf
  internal/pkg/runtime/engine/fakeroot/engine_linux.go
  internal/pkg/runtime/engine/singularity/create_linux.go
  internal/pkg/runtime/engine/singularity/prepare_linux.go
  internal/pkg/util/bin/bin.go
  internal/pkg/util/fs/squashfs/squashfs.go
  pkg/runtime/engine/config/config.go
  pkg/runtime/engine/config/parser.go
  pkg/runtime/engine/config/parser_test.go
  pkg/runtime/engine/singularity/config/config.go
  pkg/runtime/engine/singularity/config/config_linux.go
  pkg/runtime/engine/singularity/config/config_unsupported.go
Labels: CLI, Release 3.5

#4584 e2e binds tests and nested bind fix
  e2e/actions/actions.go
  internal/pkg/util/fs/layout/manager.go
Labels: Bug, Release 3.5, Testing, e2e

#4499 Verify all partitions
  pkg/signing/signing.go
Labels: CryptoSignatures, Enhancement

#4562 Check the remote.yaml permission on runtime
  cmd/internal/cli/remote.go
  cmd/internal/cli/singularity.go
  cmd/internal/cli/singularity_test.go
  internal/pkg/util/fs/helper.go
  internal/pkg/util/fs/helper_linux_test.go
  pkg/syfs/syfs.go
  pkg/sypgp/sypgp.go
  pkg/sypgp/sypgp_test.go
Labels: Bug, Enhancement

#4624 oci: Patched umoci for xattr issues
  go.mod
  go.sum
Labels: Release 3.5

#4629 Staging hosts and resolv.conf files during build
  internal/pkg/runtime/engine/imgbuild/create_linux.go
Labels: Bug, ImageBuilding, Release 3.5

#4643 Properly remove bundles with restrictive perms
  internal/pkg/util/fs/helper.go
  internal/pkg/util/fs/helper_linux_test.go
  pkg/build/types/bundle.go
Labels: Bug, Release 3.5

#4630 More improvements to the signing package
  internal/app/singularity/push.go
  internal/app/singularity/registry.go
  pkg/signing/signing.go
Labels: CryptoSignatures, Enhancement

#4646 Handle restrictive perms on base_environment makeFiles
  internal/pkg/build/sources/base_environment.go
  internal/pkg/build/sources/base_environment_test.go
Labels: Bug, Release 3.5

#4640 Remove plugin compile artifacts
  internal/app/singularity/plugin_compile_linux.go
Labels: Plugin, Release 3.5

#4644 Check plugin path exists before compile
  cmd/internal/cli/plugin_compile_linux.go
Labels: Plugin, Release 3.5

#4642 Respect plugin name during installation
  cmd/internal/cli/plugin_install_linux.go
  internal/app/singularity/plugin_install_linux.go
  internal/pkg/plugin/binary.go
Labels: Plugin, Release 3.5

#4649 Make uninstall plugin error more readable
  cmd/internal/cli/plugin_uninstall_linux.go
  internal/app/singularity/plugin_uninstall_linux.go
Labels: Plugin, Release 3.5

#4655 Add mechanism to run E2E tests using PR labels
  .circleci/config.yml
Labels: ci:e2e

#4650 Upgrade github.com/containers/image to a released version
  cmd/internal/cli/actions.go
  go.mod
  go.sum
  internal/app/singularity/pull.go
  internal/pkg/build/assemblers/sandbox_test.go
  internal/pkg/build/assemblers/sif_test.go
  internal/pkg/build/sources/conveyorPacker_oci.go
  internal/pkg/build/sources/conveyorPacker_oci_test.go
  internal/pkg/client/oci/oci.go
  internal/pkg/client/oci/oci_test.go
Labels: ci:e2e

#4616 Force PS1 through PROMPT_COMMAND to fix bash prompt
  etc/actions/exec
  etc/actions/run
  etc/actions/shell
Labels: Release 3.5, Runtime, ci:e2e

#4653 Sign/verify the system partition by default
  cmd/internal/cli/sign.go
  cmd/internal/cli/verify.go
  e2e/sign/sign.go
  e2e/verify/verify.go
  pkg/signing/signing.go
Labels: CryptoSignatures, Release 3.5, ci:e2e

#4665 Update umoci - minimize xattr warnings
  go.mod
  go.sum
Labels: ci:e2e

#4667 Restore vendor/ for release tarballs
  internal/app/singularity/plugin_compile_linux.go
  makeit/gengodep
  mlocal/frags/Makefile.stub
  mlocal/frags/go_common_opts.mk
  scripts/make-dist.sh
Labels: ci:e2e

#4661 Ask for the version number only once
  mconfig
  mlocal/frags/Makefile.stub
  scripts/make-dist.sh
Labels: ci:e2e

#4658 Get plugin manifest in a separate process
  cmd/plugin/plugin.go
  internal/app/singularity/plugin_compile_linux.go
Labels: ci:e2e

#4619 Merge ROCm support branch
  cmd/internal/cli/action_flags.go
  cmd/internal/cli/actions_linux.go
  etc/conf/singularity.conf
  etc/rocmliblist.conf
  internal/pkg/runtime/engine/singularity/container_linux.go
  mlocal/frags/build_runtime.mk
  pkg/runtime/engine/config/config.go
  pkg/runtime/engine/singularity/config/config.go
  pkg/util/gpu/devs.go
  pkg/util/gpu/paths.go
  pkg/util/nvidia/devs.go
Labels: ci:e2e

#4569 Remove the 'pull' overridden image at the last moment
  cmd/internal/cli/pull.go
  internal/app/singularity/registry.go
Labels: Enhancement, ci:e2e

#4679 Apply cgroups to instance joining processes
  e2e/instance/instance.go
  e2e/testdata/cgroups/deny_device.toml
  internal/pkg/runtime/engine/singularity/prepare_linux.go
Labels: Bug, Runtime

#4623 Add config global command to edit singularity.conf from CLI
  cmd/internal/cli/config_global_linux.go
  cmd/internal/cli/config_linux.go
  docs/content.go
  etc/conf/gen.go
  etc/conf/gen_test.go
  etc/conf/singularity.conf
  internal/app/singularity/config_global_linux.go
  mlocal/frags/build_cli.mk
  pkg/runtime/engine/config/config.go
  pkg/runtime/engine/config/parser.go
  pkg/runtime/engine/config/parser_test.go
Labels: CLI, Enhancement, ci:e2e
