Repository hpcng/singularity, pull requests merged in 2019-02, with the labels that each got.

#2595 Merge 3.0.3 changes into master
  CHANGELOG.md
Labels: scaryness

#2621 Add RPMPREFIX make rpm variable
  INSTALL.md
  dist/rpm/singularity.spec.in
  mconfig
  mlocal/frags/Makefile.stub
  mlocal/frags/build_cli.mk
  mlocal/frags/build_runtime.mk
Labels: Release 3.1.0, packaging

#2605 Definition based build E2E tests
  cmd/singularity/build_test.go
  cmd/singularity/deffile_test.go
  cmd/singularity/testdata/deffile.tmpl
Labels: Release 3.1.0, WIP

#2627 WIP Add macos as a testable platform to Travis CI
  .travis.yml
  .travis/macos/build
  .travis/macos/test
Labels: Testing, WIP, ci

#2645 Fix overlay size for root user
  internal/pkg/util/fs/layout/session.go
Labels: Release 3.1.0, bug

#2662 Test command fix
  cmd/internal/cli/actions.go
  etc/actions/test
  internal/pkg/build/sources/base_environment.go
Labels: Release 3.1.0

#2665 Refactor Build Struct
  internal/pkg/build/build.go
Labels: Release 3.1.0, bug

#2669 Allow docker environment variables override
  internal/pkg/build/sources/conveyorPacker_oci.go
Labels: Release 3.1.0, bug

#2616 Improve Error Handling In Build Package
  internal/pkg/build/assemblers/assembler_sandbox.go
  internal/pkg/build/sources/conveyorPacker_arch.go
  internal/pkg/build/sources/conveyorPacker_yum.go
  internal/pkg/build/sources/packer_ext3_linux.go
  internal/pkg/build/sources/packer_sandbox.go
  internal/pkg/build/sources/packer_sif_linux.go
  internal/pkg/build/sources/packer_squashfs.go
Labels: Release 3.1.0

#2594 Keys => Key, but not Deleting Keys
  cmd/internal/cli/key.go
  cmd/internal/cli/key_list.go
  cmd/internal/cli/key_newpair.go
  cmd/internal/cli/key_pull.go
  cmd/internal/cli/key_push.go
  cmd/internal/cli/key_search.go
  cmd/internal/cli/keys.go
  cmd/internal/cli/sign.go
  cmd/internal/cli/verify.go
  docs/content.go
Labels: Release 3.1.0, cli

#2664 App testing
  cmd/singularity/build_test.go
  cmd/singularity/deffile_test.go
  cmd/singularity/testdata/deffile.tmpl
Labels: Release 3.1.0

#2670 add docker and shub pull tests
  cmd/internal/cli/actions.go
  cmd/singularity/pull_test.go
Labels: Release 3.1.0, Testing

#2674 App test
  cmd/singularity/build_test.go
  internal/pkg/build/apps/apps.go
Labels: Release 3.1.0

#2659 Verbose when mounting default bind points
  internal/pkg/runtime/engines/singularity/container.go
Labels: Release 3.1.0

#2672 Create OCI bundle from SIF
  cmd/internal/cli/oci_linux.go
  docs/content.go
  internal/app/singularity/oci_attach_linux.go
  internal/app/singularity/oci_create_linux.go
  internal/app/singularity/oci_delete_linux.go
  internal/app/singularity/oci_exec_linux.go
  internal/app/singularity/oci_kill_linux.go
  internal/app/singularity/oci_linux.go
  internal/app/singularity/oci_mount_linux.go
  internal/app/singularity/oci_pause_linux.go
  internal/app/singularity/oci_run_linux.go
  internal/app/singularity/oci_start_linux.go
  internal/app/singularity/oci_state_linux.go
  internal/app/singularity/oci_update_linux.go
  pkg/ocibundle/bundle.go
  pkg/ocibundle/sif/bundle.go
  pkg/ocibundle/sif/bundle_test.go
  pkg/ocibundle/tools/loop.go
  pkg/ocibundle/tools/oci.go
  pkg/ocibundle/tools/overlay.go
Labels: Release 3.1.0, enhancement

#2671 Fix /tmp and /var/tmp permissions when used with contain flag
  internal/pkg/runtime/engines/singularity/container.go
  internal/pkg/util/fs/helper.go
  internal/pkg/util/fs/helper_linux_test.go
Labels: Release 3.1.0, bug

#2578 Cache List, & Cache Clean
  cmd/internal/cli/cache_clean_linux.go
  cmd/internal/cli/cache_linux.go
  cmd/internal/cli/cache_list_linux.go
  docs/content.go
  internal/app/singularity/cache_clean_linux.go
  internal/app/singularity/cache_list_linux.go
  internal/pkg/client/cache/dir.go
Labels: Documentation, Release 3.1.0, Testing, cli

#2425 Fail if tried to remote build a sandbox container
  internal/pkg/runtime/engines/singularity/container.go
Labels: Image Building

#2679 Revert GC fix as it breaks OCI engine
  internal/pkg/runtime/engines/oci/prepare.go
Labels: Release 3.1.0, bug

#2685 Set OCI default args to execute runscript
  pkg/ocibundle/sif/bundle.go
Labels: Release 3.1.0

#2684 Fix terminal issue with oci commands
  internal/app/singularity/oci_attach_linux.go
  internal/app/singularity/oci_run_linux.go
  internal/pkg/runtime/engines/oci/process.go
Labels: Release 3.1.0, bug

#2710 Fix oci kill command
  cmd/internal/cli/oci_linux.go
Labels: Release 3.1.0, bug

#2701 Remove redundant file owner checks
  internal/pkg/runtime/engines/singularity/prepare.go
Labels: Release 3.1.0, bug

#2709 Add none as mount type exception
  internal/pkg/util/fs/mount/mount.go
Labels: Release 3.1.0, bug

#2713 Fix shared mount for %setup %files during build
  internal/pkg/runtime/engines/imgbuild/create.go
  internal/pkg/runtime/engines/imgbuild/engine.go
Labels: Release 3.1.0, bug, enhancement

#2714 Fix --apply-cgroups path override
  internal/pkg/runtime/engines/singularity/container.go
Labels: Release 3.1.0, bug

#2690 Followup PR for updated INSTALL.md
  INSTALL.md
Labels: Release 3.1.0

#2715 Explicit root requirement with OCI commands
  cmd/internal/cli/oci_linux.go
  docs/content.go
  internal/pkg/runtime/engines/oci/config.go
  internal/pkg/runtime/engines/oci/create.go
  internal/pkg/runtime/engines/oci/prepare.go
Labels: Release 3.1.0, bug, cli

#2706 App Labels Envvar
  internal/pkg/build/apps/apps.go
Labels: Release 3.1.0

#2702 add a link to the EPC blog post
  README.md
Labels: Documentation, enhancement

#2738 Fix panic with empty passwd/group file in container image
  internal/pkg/util/fs/files/files_linux_test.go
  internal/pkg/util/fs/files/group.go
  internal/pkg/util/fs/files/passwd.go
Labels: Release 3.1.0, bug

#2741 always update base metadata when building
  internal/pkg/build/sources/conveyorPacker_library.go
  internal/pkg/build/sources/conveyorPacker_local.go
  internal/pkg/build/sources/conveyorPacker_shub.go
Labels: Image Building, Release 3.1.0

#2752 Set recursive mount propagation in build engine
  internal/pkg/runtime/engines/imgbuild/create.go
Labels: Release 3.1.0, bug

#2751 Double quote environment variable values in `10-docker2singularity.sh`
  internal/pkg/build/sources/conveyorPacker_oci.go
Labels: Release 3.1.0, bug

#2734 Return error with capability add/drop when no user/group specified
  internal/app/singularity/capability_manage_linux.go
Labels: Release 3.1.0, bug

#2733 Fix status report in OCI engine
  cmd/internal/cli/oci_linux.go
  internal/app/starter/master.go
  internal/app/starter/stage.go
  internal/pkg/runtime/engines/oci/create.go
  internal/pkg/runtime/engines/oci/process.go
  internal/pkg/runtime/engines/singularity/process.go
Labels: Release 3.1.0, bug

#2757 Prevent PostStartProcess from sending bad state
  internal/pkg/runtime/engines/oci/process.go
Labels: Release 3.1.1, bug

#2732 Plugin system skeleton framework
  .gitignore
  cmd/internal/cli/actions.go
  cmd/internal/cli/actions_linux.go
  cmd/internal/cli/plugin_compile_linux.go
  cmd/internal/cli/plugin_install_linux.go
  cmd/internal/cli/plugin_linux.go
  cmd/internal/cli/singularity.go
  docs/plugin.go
  examples/plugins/test-plugin/main.go
  internal/app/singularity/plugin_compile_linux.go
  internal/app/singularity/plugin_install_linux.go
  internal/pkg/plugin/binary.go
  internal/pkg/plugin/command.go
  internal/pkg/plugin/flag.go
  internal/pkg/plugin/load.go
  internal/pkg/plugin/manifestgen/main.go
  internal/pkg/plugin/registry.go
  pkg/plugin/command.go
  pkg/plugin/flag.go
  pkg/plugin/manifest.go
  pkg/plugin/plugin.go
  pkg/plugin/register.go
Labels: Release 3.2.0, feature

#2749 Add `go_import_path` to .travis.yml so user forks will build successf…
  .travis.yml
  .travis/before_install
Labels: ci

#2747 Add hidden buildcfg command to display compile-time parameters
  cmd/internal/cli/buildconfig.go
Labels: Release 3.2.0, enhancement
