Repository hpcng/singularity, pull requests merged in 2019-06, with the labels that each got.

#3677 Add a command to print the command tree for singularity
  cmd/docs/cmds/cmdtree.go
Labels: Documentation, e2e

#3660 Support for Shub caching when using 'pull'
  cmd/internal/cli/pull.go
  internal/app/singularity/pull.go
  pkg/client/shub/pull.go
Labels: Enhancement, Release 3.3.0

#3608 Alpine singularity 3.1.1 singularity 3.2.0
  dist/alpinelinux/singularity-3.1.1/APKBUILD
  dist/alpinelinux/singularity-3.2.0/APKBUILD
  dist/alpinelinux/singularity-3.2.0/c0f9abf5d9877372bff12127fd7294c2e962e1ab.patch
Labels: Packaging

#3676 Starter cleanup
  cmd/starter/c/include/starter.h
  cmd/starter/c/starter.c
  cmd/starter/main_linux.go
  internal/app/starter/master_linux.go
  internal/pkg/runtime/engines/config/starter/starter_linux.go
  internal/pkg/runtime/engines/imgbuild/engine_linux.go
  internal/pkg/runtime/engines/oci/prepare_linux.go
  internal/pkg/runtime/engines/singularity/prepare_linux.go
Labels: Enhancement, Release 3.3.0, Runtime, TechnicalDebt

#3650 Only clean cache directories that we create
  internal/app/singularity/cache_clean_linux.go
  internal/pkg/client/cache/dir.go
Labels: Bug, Release 3.3.0

#3685 Fix oversight during starter cleanup
  cmd/starter/c/starter.c
Labels: Bug, Release 3.3.0, Runtime

#3659 Add 'shub' to cache list/clean + improved '--name' handling
  cmd/internal/cli/cache_clean_linux.go
  cmd/internal/cli/cache_list_linux.go
  internal/app/singularity/cache_clean_linux.go
  internal/app/singularity/cache_list_linux.go
Labels: Bug, Enhancement, Release 3.3.0

#3702 Remove an unused check for the golang version
  mlocal/checks/basechecks.chk
Labels: Packaging

#3708 Fix problem with internal/pkg/build/sources/conveyorPacker_busybox.go
  examples/busybox/Singularity
  examples/instances/Singularity
Labels: Testing

#3682 Add caching for pulls with oras transport
  cmd/internal/cli/push.go
  go.mod
  internal/app/singularity/pull.go
  internal/app/singularity/push.go
  internal/app/singularity/util.go
  internal/pkg/client/cache/oras.go
  internal/pkg/oras/oras.go
Labels: Release 3.3.0

#3697 Starter generic container privileges setup
  cmd/starter/c/starter.c
  internal/pkg/runtime/engines/config/starter/starter_linux.go
Labels: Release 3.3.0, Runtime, TechnicalDebt

#3711 Singularity engine: rework network setup, shared mount tag addition
  internal/pkg/runtime/engines/singularity/container_linux.go
  internal/pkg/util/fs/mount/mount_linux.go
Labels: Release 3.3.0, Runtime

#3706 Starter: rework namespace join
  cmd/starter/c/starter.c
  internal/pkg/runtime/engines/singularity/create_linux.go
  internal/pkg/runtime/engines/singularity/process_linux.go
  internal/pkg/runtime/engines/singularity/rpc/args.go
  internal/pkg/runtime/engines/singularity/rpc/client/client.go
  internal/pkg/runtime/engines/singularity/rpc/server/server_linux.go
Labels: Bug, Release 3.3.0, Runtime, TechnicalDebt

#3712 Oras Support for Actions and Build commands
  cmd/internal/cli/actions.go
  e2e/actions/actions.go
  e2e/imgbuild/imgbuild.go
  e2e/internal/e2e/docker.go
  e2e/internal/e2e/imagepush.go
  e2e/push/push.go
  internal/pkg/build/build.go
  internal/pkg/build/sources/conveyorPacker_oras.go
  internal/pkg/util/uri/uri.go
Labels: Release 3.3.0

#3680 Create /dev/tty device by default with contain/minimal dev
  internal/pkg/runtime/engines/singularity/container_linux.go
Labels: Regression, Release 3.3.0, Runtime

#3681 Fix configuration bad default value and remove old configuration template file
  etc/singularity.conf.in
  pkg/runtime/engines/singularity/config/data/singularity.conf
Labels: Documentation, Release 3.3.0, TechnicalDebt

#3719 Fix pipe socket buffer size check
  internal/pkg/util/exec/pipe_linux.go
Labels: Bug, CLI, Release 3.3.0, Runtime

#3724 Clean environment by setting variables to empty string rather than NULL
  cmd/starter/c/starter.c
Labels: Bug, Release 3.3.0, Runtime

#3723 Fix SELinux unconfined test
  internal/pkg/security/security_test.go
Labels: Bug, Release 3.3.0, Testing

#2718 Fakeroot feature
  cmd/internal/cli/action_flags.go
  cmd/internal/cli/actions_linux.go
  cmd/internal/cli/build.go
  cmd/internal/cli/build_linux.go
  cmd/starter/c/starter.c
  etc/network/40_fakeroot.conflist
  internal/pkg/build/build.go
  internal/pkg/build/stage.go
  internal/pkg/fakeroot/fakeroot.go
  internal/pkg/fakeroot/fakeroot_test.go
  internal/pkg/runtime/engines/imgbuild/create_linux.go
  internal/pkg/runtime/engines/imgbuild/engine_linux.go
  internal/pkg/runtime/engines/singularity/cleanup_linux.go
  internal/pkg/runtime/engines/singularity/container_linux.go
  internal/pkg/runtime/engines/singularity/prepare_linux.go
  internal/pkg/util/priv/priv_linux.go
  mlocal/frags/build_network.mk
  pkg/build/types/bundle.go
  pkg/network/network_linux.go
  pkg/runtime/engines/singularity/config/config.go
  pkg/runtime/engines/singularity/config/data/singularity.conf
Labels: BehaviorChange, Enhancement, Release 3.3.0, Runtime

#3736 Fixed panic when exec/run a container in the library that does not exist
  cmd/internal/cli/actions.go
  internal/app/singularity/pull.go
  internal/pkg/build/sources/conveyorPacker_library.go
Labels: Bug, Release 3.3.0

#3745 Check if the container exist, and print user-friendly error if not
  cmd/internal/cli/verify.go
Labels: Enhancement, Release 3.4

#3749 Update help docs to include oras transport
  docs/content.go
Labels: CherryPick, Documentation, Release 3.3.0

#3746 Maybe slightly "improved" base environment
  etc/actions/run
  etc/actions/test
  internal/pkg/build/sources/base_environment.go
Labels: BehaviorChange, Question

#3791 Oras context fix
  cmd/internal/cli/push.go
  internal/pkg/oras/oras.go
Labels: CherryPick, Release 3.3.0

#3796 Update the help for remote commands that use a default value for the remote name
  docs/remote.go
Labels: CherryPick, Documentation, Release 3.3.0

#3760 e2e privileges and test execution context
  e2e/actions/actions.go
  e2e/docker/docker.go
  e2e/env/env.go
  e2e/help/help.go
  e2e/imgbuild/imgbuild.go
  e2e/instance/instance.go
  e2e/internal/e2e/docker.go
  e2e/internal/e2e/env.go
  e2e/internal/e2e/fileutil.go
  e2e/internal/e2e/image.go
  e2e/internal/e2e/imagepush.go
  e2e/internal/e2e/priv_linux.go
  e2e/internal/e2e/singularitycmd.go
  e2e/pull/pull.go
  e2e/push/push.go
  e2e/remote/remote.go
  e2e/suite.go
  e2e/version/version.go
  go.mod
  go.sum
  vendor/github.com/Netflix/go-expect/.travis.yml
  vendor/github.com/Netflix/go-expect/Gopkg.lock
  vendor/github.com/Netflix/go-expect/Gopkg.toml
  vendor/github.com/Netflix/go-expect/LICENSE
  vendor/github.com/Netflix/go-expect/OSSMETADATA
  vendor/github.com/Netflix/go-expect/README.md
  vendor/github.com/Netflix/go-expect/console.go
  vendor/github.com/Netflix/go-expect/doc.go
  vendor/github.com/Netflix/go-expect/expect.go
  vendor/github.com/Netflix/go-expect/expect_opt.go
  vendor/github.com/Netflix/go-expect/passthrough_pipe.go
  vendor/github.com/Netflix/go-expect/reader_lease.go
  vendor/github.com/Netflix/go-expect/test_log.go
  vendor/modules.txt
Labels: Enhancement, Testing, e2e

#3696 Fix parent process signal propagation
  internal/app/starter/master_linux.go
  internal/pkg/runtime/engines/singularity/monitor.go
  internal/pkg/runtime/engines/singularity/prepare_linux.go
  internal/pkg/runtime/engines/singularity/process_linux.go
  pkg/runtime/engines/singularity/config/config.go
Labels: BehaviorChange, Bug, CherryPick, Release 3.3.0, Runtime

#3811 Fix e2e tests privileges escalation issues and remove docker dependency
  e2e/actions/actions.go
  e2e/internal/e2e/docker.go
  e2e/internal/e2e/image.go
  e2e/internal/e2e/imageverify.go
  e2e/internal/e2e/singularitycmd.go
  e2e/suite.go
  e2e/testdata/Docker_registry.def
  mlocal/frags/Makefile.stub
Labels: Bug, e2e

#3813 Update the circleci config to version 2.1
  .circleci/config.yml
Labels: ContinuousIntegration

#3759 Fix user namespace mappings and build section execution context
  internal/pkg/fakeroot/fakeroot.go
  internal/pkg/fakeroot/fakeroot_test.go
  internal/pkg/runtime/engines/engines_linux.go
  internal/pkg/runtime/engines/imgbuild/create_linux.go
  internal/pkg/runtime/engines/imgbuild/process_linux.go
  internal/pkg/runtime/engines/imgbuild/rpc/args.go
  internal/pkg/runtime/engines/imgbuild/rpc/client/client.go
  internal/pkg/runtime/engines/imgbuild/rpc/server/server_linux.go
  pkg/runtime/engines/singularity/config/data/singularity.conf
Labels: Bug, CherryPick, ImageBuilding, Release 3.3.0

#3780 Allow execution from a parent (rootless) user namespace
  cmd/internal/cli/actions_linux.go
  internal/pkg/runtime/engines/imgbuild/engine_linux.go
  internal/pkg/runtime/engines/singularity/container_linux.go
  internal/pkg/runtime/engines/singularity/process_linux.go
  pkg/util/namespaces/user_linux.go
Labels: Bug, CherryPick, Release 3.3.0, Runtime

#3825 Fix bad pull library URI variable introduces during CLI refactoring
  cmd/internal/cli/pull.go
  e2e/pull/pull.go
Labels: Bug, CLI, CherryPick, Regression, Release 3.3.0
