Repository hpcng/singularity, pull requests merged in 2019-05, with the labels that each got.

#3230 CLI command/flag manager
  cmd/internal/cli/action_flags.go
  cmd/internal/cli/action_flags_darwin.go
  cmd/internal/cli/action_flags_linux.go
  cmd/internal/cli/actions.go
  cmd/internal/cli/build.go
  cmd/internal/cli/buildconfig.go
  cmd/internal/cli/cache_clean_linux.go
  cmd/internal/cli/cache_linux.go
  cmd/internal/cli/cache_list_linux.go
  cmd/internal/cli/capability_add_linux.go
  cmd/internal/cli/capability_avail_linux.go
  cmd/internal/cli/capability_drop_linux.go
  cmd/internal/cli/capability_linux.go
  cmd/internal/cli/capability_list_linux.go
  cmd/internal/cli/cli_test.go
  cmd/internal/cli/inspect_linux.go
  cmd/internal/cli/instance_linux.go
  cmd/internal/cli/instance_list_linux.go
  cmd/internal/cli/instance_start_linux.go
  cmd/internal/cli/instance_stop_linux.go
  cmd/internal/cli/key.go
  cmd/internal/cli/key_export.go
  cmd/internal/cli/key_import.go
  cmd/internal/cli/key_list.go
  cmd/internal/cli/key_newpair.go
  cmd/internal/cli/key_pull.go
  cmd/internal/cli/key_push.go
  cmd/internal/cli/key_remove.go
  cmd/internal/cli/key_search.go
  cmd/internal/cli/oci_linux.go
  cmd/internal/cli/plugin_compile_linux.go
  cmd/internal/cli/plugin_install_linux.go
  cmd/internal/cli/plugin_linux.go
  cmd/internal/cli/pull.go
  cmd/internal/cli/push.go
  cmd/internal/cli/remote.go
  cmd/internal/cli/run_help_linux.go
  cmd/internal/cli/search.go
  cmd/internal/cli/sign.go
  cmd/internal/cli/singularity.go
  cmd/internal/cli/verify.go
  go.mod
  pkg/cmdline/cmd.go
  pkg/cmdline/cmd_test.go
  pkg/cmdline/env.go
  pkg/cmdline/env_test.go
  pkg/cmdline/flag.go
  pkg/cmdline/flag_test.go
  vendor/github.com/magiconair/properties/LICENSE
  vendor/github.com/magiconair/properties/assert/assert.go
  vendor/modules.txt
Labels: CLI, Release 3.3.0, TechnicalDebt

#3416 [E2E] Tests for Docker
  cmd/singularity/docker_test.go
  e2e/docker/docker.go
  e2e/internal/e2e/imagebuild.go
  e2e/suite.go
Labels: Release 3.3.0, Testing, e2e

#3468 Add a corner case test to pkg/util/capabilities
  pkg/util/capabilities/capabilities_test.go
Labels: Release 3.3.0, Testing

#3471 Slightly improved error message when pushing a image to the library that already exist
  pkg/client/library/push.go
Labels: Release 3.3.0

#3432 '--allow-unauthenticated' => '--allow-unsigned'
  cmd/internal/cli/pull.go
Labels: CherryPick, Release 3.2.0, Release 3.3.0

#3436 Changelog update
  CHANGELOG.md
Labels: Documentation, Release 3.2.0

#3475 Return error instead of explicitly failing
  internal/app/singularity/cache_list_linux.go
Labels: Release 3.3.0, Testing

#3469 Updated 'cache clean' docs
  docs/content.go
Labels: Release 3.3.0

#3435 Migrate Definition Build Tests to E2E Framework
  cmd/singularity/build_test.go
  cmd/singularity/deffile_test.go
  e2e/docker/docker.go
  e2e/imgbuild/imgbuild.go
  e2e/internal/e2e/fileutil.go
  e2e/internal/e2e/imagebuild.go
  e2e/internal/e2e/imageexec.go
  e2e/internal/e2e/imageverify.go
  e2e/testdata/deffile.tmpl
Labels: DefinitionFile, ImageBuilding, Testing, e2e

#3489 Port help test to e2e
  cmd/singularity/help_test.go
  e2e/help/help.go
  e2e/suite.go
Labels: Testing, e2e

#3456 Allow use of custom --home with 'mount home = no'
  internal/pkg/runtime/engines/singularity/container_linux.go
Labels: Bug, Regression, Release 3.3.0

#3390 Combine 'apps' With 'inspect'
  cmd/internal/cli/apps_linux.go
  cmd/internal/cli/inspect_linux.go
  docs/content.go
Labels: Release 3.3.0

#3505 add hostname to definition file
  e2e/testdata/Singularity
Labels: Bug, Testing, e2e

#3299 Fix terminal issue when piping commands
  cmd/starter/c/starter.c
  internal/app/starter/master_linux.go
  internal/pkg/runtime/engines/singularity/monitor.go
  internal/pkg/runtime/engines/singularity/process_linux.go
Labels: Bug, Release 3.3.0

#3497 Add content tests for the oci help commands
  e2e/help/help.go
  e2e/testdata/help/help-oci-attach.txt
  e2e/testdata/help/help-oci-create.txt
  e2e/testdata/help/help-oci-delete.txt
  e2e/testdata/help/help-oci-exec.txt
  e2e/testdata/help/help-oci-kill.txt
  e2e/testdata/help/help-oci-mount.txt
  e2e/testdata/help/help-oci-pause.txt
  e2e/testdata/help/help-oci-resume.txt
  e2e/testdata/help/help-oci-run.txt
  e2e/testdata/help/help-oci-start.txt
  e2e/testdata/help/help-oci-state.txt
  e2e/testdata/help/help-oci-umount.txt
  e2e/testdata/help/help-oci-update.txt
  e2e/testdata/help/help-oci.txt
  go.mod
  internal/pkg/test/cmd.go
  vendor/github.com/google/go-cmp/LICENSE
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/debug_disable.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/debug_enable.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/diff.go
  vendor/github.com/google/go-cmp/cmp/internal/function/func.go
  vendor/github.com/google/go-cmp/cmp/internal/value/format.go
  vendor/github.com/google/go-cmp/cmp/internal/value/sort.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/reporter.go
  vendor/github.com/google/go-cmp/cmp/unsafe_panic.go
  vendor/github.com/google/go-cmp/cmp/unsafe_reflect.go
  vendor/gotest.tools/LICENSE
  vendor/gotest.tools/assert/assert.go
  vendor/gotest.tools/assert/cmp/compare.go
  vendor/gotest.tools/assert/cmp/result.go
  vendor/gotest.tools/assert/result.go
  vendor/gotest.tools/golden/golden.go
  vendor/gotest.tools/icmd/command.go
  vendor/gotest.tools/icmd/exitcode.go
  vendor/gotest.tools/icmd/ops.go
  vendor/gotest.tools/internal/difflib/LICENSE
  vendor/gotest.tools/internal/difflib/difflib.go
  vendor/gotest.tools/internal/format/diff.go
  vendor/gotest.tools/internal/format/format.go
  vendor/gotest.tools/internal/source/defers.go
  vendor/gotest.tools/internal/source/source.go
  vendor/modules.txt
Labels: OCI, Testing, e2e

#3514 Removed Unused, dead code
  cmd/internal/cli/pull.go
Labels: Release 3.3.0

#3520 Improve testing coverage of internal/pkg/client/oci
  internal/pkg/client/oci/oci_test.go
  internal/pkg/client/oci/transports_test.go
Labels: Testing

#3523 Pull public key by ID (Last 8 characters)
  cmd/internal/cli/key_pull.go
  go.mod
  go.sum
  pkg/sypgp/sypgp.go
  vendor/github.com/sylabs/scs-key-client/client/client.go
  vendor/github.com/sylabs/scs-key-client/client/pks.go
  vendor/github.com/sylabs/scs-key-client/client/version.go
  vendor/modules.txt
Labels: PGPCrypto, Release 3.3.0

#3543 Remove macos testing from travis
  .travis.yml
  .travis/macos/build
  .travis/macos/test
Labels: ContinuousIntegration

#3495 Fix CLI env parsing
  cmd/internal/cli/singularity.go
  pkg/cmdline/cmd.go
  pkg/cmdline/flag.go
  pkg/cmdline/flag_test.go
Labels: Bug, CLI, Release 3.3.0

#3506 Improved error when pushing a unsigned container
  cmd/internal/cli/push.go
Labels: Release 3.3.0

#3572 Fix the man page installation for custom install prefixes
  cmd/docs/docs.go
  mlocal/frags/Makefile.stub
Labels: Bug, Packaging

#3574 Create scripts/go-test script during build
  mconfig
  mlocal/frags/build_scripts.mk
  scripts/.gitignore
  scripts/expand-env.go
  scripts/go-test.in
Labels: Testing

#3575 Configure the 'sypgp' dir with 'SINGULARITY_SYPGPDIR'
  docs/content.go
  pkg/sypgp/sypgp.go
Labels: Release 3.3.0

#3577 Removed redundant sypgp variables
  pkg/sypgp/sypgp.go
Labels: Release 3.3.0

#3586 Fix instance join regression with root user
  internal/pkg/runtime/engines/singularity/prepare_linux.go
Labels: Bug, CherryPick, Regression, Release 3.2.0

#3588 Automatically bind nvidia persistenced socket with --nv
  cmd/internal/cli/actions_linux.go
  pkg/util/nvidia/paths.go
Labels: Enhancement, Release 3.3.0

#3589 Fix cgroup test panic
  internal/pkg/cgroups/cgroups_linux_test.go
Labels: Bug, Release 3.3.0, Testing

#3593 Removed Extra TIP pointing to 'sylabs.io/docs' when pushing a unsigned container
  internal/app/singularity/push.go
Labels: Release 3.3.0

#3614 Fixed panic when pulling a container that does not exist
  internal/app/singularity/pull.go
Labels: Bug

#3631 [E2E] Tests for version: verifying semver
  e2e/version/version.go
Labels: Testing, e2e

#3599 Prevent session final directory to be overridden by user binds.
  internal/pkg/runtime/engines/singularity/container_linux.go
  internal/pkg/runtime/engines/singularity/prepare_linux.go
  internal/pkg/runtime/engines/singularity/rpc/args.go
  internal/pkg/runtime/engines/singularity/rpc/client/client.go
  internal/pkg/runtime/engines/singularity/rpc/server/server_linux.go
  internal/pkg/util/mainthread/mainthread.go
Labels: Bug, Release 3.3.0

#3637 Fix starter environment variable cleanup
  cmd/starter/c/include/message.h
  cmd/starter/c/message.c
  cmd/starter/c/starter.c
  cmd/starter/main_linux.go
Labels: Release 3.3.0, TechnicalDebt
