Repository hpcng/singularity, pull requests merged in 2019-04, with the labels that each got.

#3177 Support Sandbox Image on macOS
  cmd/internal/cli/startvm_darwin.go
Labels: Release 3.2.0

#3178 Generate 9p Mount Tag on Bind Mount
  cmd/internal/cli/startvm_darwin.go
Labels: Release 3.2.0

#2974 Prealloc slices where possible
  internal/app/singularity/remote_list.go
  internal/app/singularity/remote_status.go
  internal/pkg/runtime/engines/config/starter/starter_linux.go
  internal/pkg/runtime/engines/oci/prepare_linux.go
  internal/pkg/runtime/engines/oci/process_linux.go
  pkg/signing/signing.go
  pkg/util/capabilities/capabilities.go
Labels: Release 3.2.0, TechnicalDebt

#2817 Print usage information if an invalid flag is passed to singularity
  cmd/internal/cli/singularity.go
  cmd/internal/cli/term_other.go
  cmd/internal/cli/term_unix.go
Labels: Release 3.2.0

#3195 Consolidate image package and make SIF image code more generic
  cmd/internal/cli/actions_linux.go
  internal/pkg/runtime/engines/singularity/prepare_linux.go
  pkg/image/ext3.go
  pkg/image/image.go
  pkg/image/image_test.go
  pkg/image/sandbox.go
  pkg/image/sif.go
  pkg/image/squashfs.go
  pkg/ocibundle/sif/bundle_linux.go
Labels: Bug, Enhancement, Release 3.2.0

#3187 CLI capability fix
  pkg/util/capabilities/config.go
  pkg/util/capabilities/config_test.go
Labels: CherryPick, Enhancement, Release 3.1.1

#3188 Check if an instance is not started from another one
  cmd/internal/cli/actions_linux.go
Labels: Bug, CherryPick, Release 3.1.1

#3131 Improve testing coverage for the build/types package.
  pkg/build/types/bundle_test.go
  pkg/build/types/definition_test.go
Labels: Release 3.2.0, Testing

#3181 Update Bind Mount Handling
  cmd/internal/cli/startvm_darwin.go
Labels: Release 3.2.0

#3142 Provide instructions for installing golangci-lint
  CONTRIBUTING.md
  INSTALL.md
Labels: Release 3.2.0

#3263 Remove the `GOCACHE` environment variable from the circleci configuration
  .circleci/config.yml
Labels: ContinuousIntegration, Regression, Release 3.2.0, Testing

#3196 Add tests for internal/pkg/security
  internal/pkg/security/security_test.go
Labels: Release 3.2.0, Testing

#3117 Key export command
  cmd/internal/cli/key.go
  cmd/internal/cli/key_export.go
  cmd/internal/cli/key_import.go
  docs/content.go
  pkg/signing/signing.go
  pkg/sypgp/sypgp.go
Labels: Release 3.2.0

#3236 Add capability warning if unknown or not authorized
  internal/pkg/runtime/engines/singularity/prepare_linux.go
Labels: CherryPick, Enhancement, Release 3.1.1

#3237 Fix cgroups resource typo
  internal/pkg/cgroups/cgroups_linux.go
  internal/pkg/runtime/engines/oci/create_linux.go
  internal/pkg/runtime/engines/singularity/container_linux.go
Labels: CherryPick, Release 3.1.1

#3238 Add missing bundle argument requirement for oci create/run help commands
  docs/content.go
Labels: CherryPick, Documentation, Release 3.1.1

#3258 Fix building plugins in combination with Go modules
  cmd/internal/cli/actions_linux.go
  cmd/internal/cli/apps_linux.go
  cmd/internal/cli/inspect_linux.go
  cmd/internal/cli/run_help_linux.go
  cmd/plugin_manifestgen/main.go
  docs/plugin.go
  etc/conf/gen.go
  examples/plugins/test-plugin/README.md
  examples/plugins/test-plugin/main.go
  internal/app/singularity/plugin_compile_linux.go
  internal/pkg/build/assemblers/assembler_sif.go
  internal/pkg/plugin/flag.go
  internal/pkg/runtime/engines/engines_linux.go
  internal/pkg/runtime/engines/singularity/create_linux.go
  internal/pkg/runtime/engines/singularity/engine.go
  internal/pkg/runtime/engines/singularity/prepare_linux.go
  mlocal/frags/build_cli.mk
  mlocal/frags/go_common_opts.mk
  pkg/plugin/flag.go
  pkg/runtime/engines/singularity/config/config.go
  pkg/runtime/engines/singularity/config/config_linux.go
  pkg/runtime/engines/singularity/config/config_unsupported.go
  pkg/runtime/engines/singularity/config/data/singularity.conf
Labels: Release 3.2.0

#3254 Perform basic architecture check in the starter
  pkg/image/sif.go
Labels: BehaviorChange, Enhancement, Release 3.2.0

#2712 Warning When push/pull a unsigned container
  .travis/macos/test
  cmd/internal/cli/key_pull.go
  cmd/internal/cli/pull.go
  cmd/internal/cli/push.go
  cmd/internal/cli/singularity.go
  cmd/singularity/pull_test.go
  docs/content.go
  pkg/signing/signing.go
Labels: Release 3.2.0

#3291 update remote docs
  docs/remote.go
Labels: CherryPick, Release 3.2.0

#3293 Throw a warning if seccomp is used and not enabled
  cmd/singularity/instance_test.go
  internal/pkg/security/security.go
Labels: Bug, CherryPick, Release 3.2.0

#3288 Document fact that --contain ignores bind paths
  pkg/runtime/engines/singularity/config/data/singularity.conf
Labels: CherryPick, Documentation, Release 3.2.0

#3301 Remove deprecated plugin hooks
  internal/pkg/plugin/command.go
  pkg/plugin/command.go
Labels: Documentation, Release 3.2.0

#3295 multistage definition example
  examples/multistage/Singularity
Labels: CherryPick, Release 3.2.0

#3267 Add the vendor-check target to our code checking steps in the circleci configuration
  .circleci/config.yml
Labels: ContinuousIntegration, FeatureRequest, Testing

#3367 Split the e2e-test makefile target into two targets so either set of tests can be run by themselves.
  .circleci/config.yml
  mlocal/frags/Makefile.stub
Labels: Testing

#3180 Update Help for 'key' Command
  docs/content.go
Labels: CherryPick, Release 3.2.0

#3359 Sign Offline
  cmd/internal/cli/sign.go
  pkg/signing/signing.go
Labels: Release 3.3.0

#3394 OCI engine: empty mount destination file
  internal/pkg/runtime/engines/oci/create_linux.go
Labels: Bug, Release 3.3.0

#3384 Add a README which includes an example of how to add a test
  e2e/README.md
Labels: Documentation, Testing

#3397 Change plugin API CommandAdder -> CommandHook
  cmd/internal/cli/singularity.go
  examples/plugins/test-plugin/main.go
  internal/pkg/plugin/command.go
  internal/pkg/plugin/flag.go
  internal/pkg/plugin/registry.go
  pkg/plugin/command.go
  pkg/plugin/register.go
Labels: CherryPick, Release 3.2.0, TechnicalDebt

#3358 Add 'SINGULARITY_PULLPATH'
  cmd/internal/cli/pull.go
  cmd/internal/cli/singularity.go
  cmd/singularity/pull_test.go
Labels: Release 3.3.0

#3370 Improve Pull Tests
  cmd/singularity/pull_test.go
Labels: Release 3.3.0, Testing

#3296 Cache Docker Pulls as SIFs
  cmd/internal/cli/pull.go
Labels: Enhancement, Release 3.3.0

#3413 path => dir
  cmd/internal/cli/pull.go
  cmd/singularity/pull_test.go
Labels: Release 3.3.0

#3396 Improve testing coverage of internal/app/singularity
  internal/app/singularity/remote_add.go
  internal/app/singularity/remote_add_test.go
  internal/app/singularity/remote_remove_test.go
Labels: Release 3.3.0, Testing

#3297 Improve test coverage of pkg/image
  pkg/image/ext3_test.go
  pkg/image/image.go
  pkg/image/image_test.go
  pkg/image/sandbox_test.go
  pkg/image/squashfs_test.go
Labels: Release 3.3.0, Testing

#3335 Improve test coverage of internal/pkg/client/cache
  internal/pkg/client/cache/cache_test.go
  internal/pkg/client/cache/dir_test.go
  internal/pkg/client/cache/library_test.go
  internal/pkg/client/cache/net_test.go
  internal/pkg/client/cache/oci_test.go
  internal/pkg/client/cache/shub_test.go
Labels: Release 3.3.0, Testing

#3329 More Verbose When Pulling a Container Without a Tag
  internal/pkg/libexec/pull.go
  pkg/client/library/api.go
  pkg/client/library/pull.go
Labels: Release 3.3.0

#3336 Removed Tabs/Newlines From Error Returns
  internal/pkg/remote/remote.go
  pkg/client/library/api.go
Labels: Release 3.3.0

#3427 Ignore the e2e directory when doing unit tests
  mlocal/frags/Makefile.stub
Labels: ContinuousIntegration, Testing

#3429 Add EnsureImage function to make sure a test image exists
  e2e/actions/actions.go
  e2e/actions/actions_utils.go
  e2e/imgbuild/imgbuild.go
  e2e/internal/e2e/env.go
  e2e/internal/e2e/image.go
  e2e/internal/e2e/imagebuild.go
  e2e/pull/pull.go
  e2e/suite.go
Labels: e2e

#3423 Fix out of bound for starter GID array
  internal/pkg/runtime/engines/config/starter/starter_linux.go
Labels: Bug, CherryPick, Release 3.2.0

#3419 Fix false warning when seccomp is disabled
  internal/pkg/security/seccomp/seccomp_unsupported.go
  internal/pkg/security/security.go
Labels: Bug, CherryPick, Release 3.2.0

#3420 Fix private mount propagation
  internal/pkg/runtime/engines/config/starter/starter_linux.go
Labels: Bug, CherryPick, Release 3.2.0

#3431 Check the Go compiler during mconfig
  mconfig
  mlocal/checks/basechecks.chk
  mlocal/checks/version.go
  mlocal/frags/go_common_opts.mk
Labels: CherryPick, Release 3.2.0
