Repository hpcng/singularity, pull requests merged in 2019-03, with the labels that each got.

#2800 Remove warning when CWD doesn't exist on host
  internal/pkg/runtime/engines/singularity/container.go
Labels: Release 3.2.0, bug

#2776 Add Shub Image Caching
  CONTRIBUTORS.md
  cmd/internal/cli/actions.go
Labels: Image Building, behavior change

#2804 Set -trimpath flags in appropriate sections of mconfig
  mlocal/frags/Makefile.stub
  mlocal/frags/build_cli.mk
  mlocal/frags/build_network.mk
  mlocal/frags/build_runtime.mk
  mlocal/frags/go_common_opts.mk
Labels: Release 3.2.0, tech debt

#2801 OCI Config Embedding In SIF
  internal/pkg/build/assemblers/assembler_sif.go
  internal/pkg/build/sources/conveyorPacker_oci.go
  pkg/build/types/bundle.go
Labels: OCI, Release 3.2.0

#2675 Enable execution on Mac OS X
  cmd/internal/cli/action_flags.go
  cmd/internal/cli/action_flags_darwin.go
  cmd/internal/cli/action_flags_linux.go
  cmd/internal/cli/actions.go
  cmd/internal/cli/actions_unsupported.go
  cmd/internal/cli/instance_start_linux.go
  cmd/internal/cli/pull.go
  cmd/internal/cli/singularity.go
  cmd/internal/cli/startvm.go
  cmd/internal/cli/startvm_darwin.go
  cmd/internal/cli/startvm_linux.go
Labels: tech debt

#2762 Add compiler option checks
  mconfig
  mlocal/checks/basechecks.chk
  mlocal/checks/project-post.chk
  mlocal/frags/build_runtime.mk
  mlocal/frags/common_opts.mk
Labels: Release 3.2.0, bug, enhancement

#2822 Compile plugins using -trimpath flag
  cmd/internal/cli/plugin_compile_linux.go
  cmd/plugin_manifestgen/main.go
  internal/app/singularity/plugin_compile_linux.go
Labels: Release 3.2.0, tech debt

#2830 Update copyright header in plugin files to be current
  cmd/internal/cli/plugin_compile_linux.go
  cmd/internal/cli/plugin_install_linux.go
  cmd/internal/cli/plugin_linux.go
  cmd/plugin_manifestgen/main.go
  docs/plugin.go
  examples/plugins/test-plugin/main.go
  internal/app/singularity/plugin_compile_linux.go
  internal/app/singularity/plugin_install_linux.go
  internal/pkg/plugin/binary.go
  internal/pkg/plugin/command.go
  internal/pkg/plugin/flag.go
  internal/pkg/plugin/load.go
  internal/pkg/plugin/registry.go
  pkg/plugin/command.go
  pkg/plugin/flag.go
  pkg/plugin/manifest.go
  pkg/plugin/plugin.go
  pkg/plugin/register.go
Labels: Release 3.2.0, license

#2799 Image package enhancements
  internal/pkg/build/sources/conveyorPacker_local.go
  internal/pkg/image/ext3.go
  internal/pkg/image/image.go
  internal/pkg/image/image_test.go
  internal/pkg/image/reader.go
  internal/pkg/image/sandbox.go
  internal/pkg/image/sif.go
  internal/pkg/image/squashfs.go
  internal/pkg/image/unpacker/squashfs.go
  internal/pkg/image/unpacker/squashfs_test.go
  internal/pkg/runtime/engines/singularity/container.go
  internal/pkg/runtime/engines/singularity/prepare.go
  pkg/ocibundle/sif/bundle.go
Labels: Release 3.2.0, enhancement

#2823 If we are missing files, add the URL for more information.
  cmd/internal/cli/startvm.go
Labels: Documentation, Release 3.2.0

#2755 Sylog dummy functions
  internal/pkg/sylog/doc.go
  internal/pkg/sylog/sylog.go
  internal/pkg/sylog/sylog_dummy.go
  mlocal/frags/go_common_opts.mk
Labels: Release 3.2.0, Testing, Unit tests

#2760 Add tests for pkg/network package
  .travis/rpmbuild_test
  pkg/network/network.go
  pkg/network/network_test.go
Labels: Release 3.2.0, Unit tests

#2838 Fix URI usage with user namespace
  cmd/internal/cli/actions_linux.go
  cmd/singularity/actions_test.go
  internal/pkg/runtime/engines/singularity/cleanup.go
  internal/pkg/runtime/engines/singularity/config/config.go
Labels: Release 3.2.0, regression

#2850 Describe plugin naming scheme in Manifest.Name comment
  pkg/plugin/manifest.go
Labels: Documentation

#2854 Make image package public
  cmd/internal/cli/actions_linux.go
  internal/pkg/build/build.go
  internal/pkg/build/sources/conveyorPacker_local.go
  internal/pkg/runtime/engines/singularity/config/config.go
  internal/pkg/runtime/engines/singularity/container.go
  internal/pkg/runtime/engines/singularity/prepare.go
  pkg/image/doc.go
  pkg/image/ext3.go
  pkg/image/image.go
  pkg/image/image_test.go
  pkg/image/reader.go
  pkg/image/sandbox.go
  pkg/image/sif.go
  pkg/image/squashfs.go
  pkg/image/unpacker/squashfs.go
  pkg/image/unpacker/squashfs_test.go
  pkg/ocibundle/sif/bundle.go
Labels: Release 3.2.0

#2852 Fix read-only/masked path issue
  internal/pkg/runtime/engines/oci/create.go
Labels: Release 3.1.1, Release 3.2.0, bug

#2837 ocibundle package: update OCI runtime configuration
  pkg/ocibundle/sif/bundle.go
  pkg/ocibundle/sif/bundle_test.go
  pkg/ocibundle/tools/oci.go
Labels: Release 3.2.0, enhancement

#2859 Add handling for passing our CWD
  cmd/internal/cli/startvm_darwin.go
Labels: MacOS, Release 3.2.0, SingularityDesktop

#2829 SCS Remote Management
  Gopkg.lock
  Gopkg.toml
  cmd/internal/cli/build.go
  cmd/internal/cli/build_darwin.go
  cmd/internal/cli/build_linux.go
  cmd/internal/cli/key_pull.go
  cmd/internal/cli/key_push.go
  cmd/internal/cli/pull.go
  cmd/internal/cli/push.go
  cmd/internal/cli/remote.go
  cmd/internal/cli/singularity.go
  cmd/singularity/remote_test.go
  docs/remote.go
  internal/app/singularity/remote_add.go
  internal/app/singularity/remote_list.go
  internal/app/singularity/remote_login.go
  internal/app/singularity/remote_remove.go
  internal/app/singularity/remote_status.go
  internal/app/singularity/remote_use.go
  internal/pkg/remote/remote.go
  internal/pkg/remote/remote_test.go
  vendor/gopkg.in/yaml.v2/encode.go
Labels: Release 3.2.0, SCS, cli

#2781 Key import command
  Gopkg.lock
  cmd/internal/cli/key.go
  cmd/internal/cli/key_import.go
  docs/content.go
  pkg/sypgp/sypgp.go
Labels: enhancement

#2857 Do not list all plugins when uninstalling
  internal/pkg/plugin/binary.go
Labels: Release 3.2.0, TechnicalDebt

#2874 Implement plugin enable / disable
  cmd/internal/cli/plugin_disable_linux.go
  cmd/internal/cli/plugin_enable_linux.go
  cmd/internal/cli/plugin_linux.go
  docs/plugin.go
  internal/app/singularity/plugin_disable_linux.go
  internal/app/singularity/plugin_enable_linux.go
  internal/pkg/plugin/binary.go
Labels: Release 3.2.0

#2821 Dont Store Public Key When Verifying a Container
  pkg/signing/signing.go
  pkg/sypgp/sypgp.go
Labels: Release 3.2.0

#2896 Create container /dev/xxxx parent directory
  internal/pkg/runtime/engines/oci/create.go
Labels: Bug, CherryPick, Release 3.1.1

#2884 Fix `go vet` for macos
  .circleci/config.yml
  cmd/starter/main_linux.go
  internal/app/starter/master_linux.go
  internal/app/starter/rpc_linux.go
  internal/app/starter/stage_linux.go
  internal/pkg/cgroups/cgroups_linux.go
  internal/pkg/cgroups/cgroups_linux_test.go
  internal/pkg/cgroups/config_linux.go
  internal/pkg/instance/instance_linux.go
  internal/pkg/runtime/engines/config/starter/starter_linux.go
  internal/pkg/runtime/engines/engines_linux.go
  internal/pkg/runtime/engines/imgbuild/create_linux.go
  internal/pkg/runtime/engines/imgbuild/engine_linux.go
  internal/pkg/runtime/engines/imgbuild/process_linux.go
  internal/pkg/runtime/engines/oci/cleanup_linux.go
  internal/pkg/runtime/engines/oci/config_linux.go
  internal/pkg/runtime/engines/oci/create_linux.go
  internal/pkg/runtime/engines/oci/engine_linux.go
  internal/pkg/runtime/engines/oci/monitor_linux.go
  internal/pkg/runtime/engines/oci/prepare_linux.go
  internal/pkg/runtime/engines/oci/process_linux.go
  internal/pkg/runtime/engines/oci/rpc/server/server_linux.go
  internal/pkg/runtime/engines/singularity/cleanup_linux.go
  internal/pkg/runtime/engines/singularity/container_linux.go
  internal/pkg/runtime/engines/singularity/create_linux.go
  internal/pkg/runtime/engines/singularity/prepare_linux.go
  internal/pkg/runtime/engines/singularity/process_linux.go
  internal/pkg/runtime/engines/singularity/rpc/server/server_linux.go
  internal/pkg/test/privilege_darwin.go
  internal/pkg/test/privilege_linux.go
  internal/pkg/util/fs/layout/layer/overlay/overlay_linux.go
  internal/pkg/util/fs/layout/layer/underlay/underlay_linux.go
  internal/pkg/util/fs/layout/session_linux.go
  internal/pkg/util/fs/mount/mount_linux.go
  internal/pkg/util/fs/mount/mount_linux_test.go
  internal/pkg/util/fs/mount/system_linux.go
  internal/pkg/util/fs/mount/system_linux_test.go
  internal/pkg/util/priv/priv_linux.go
  internal/pkg/util/signal/signal_linux.go
  internal/pkg/util/signal/signal_linux_test.go
  mlocal/frags/build_runtime.mk
  pkg/network/network_linux.go
  pkg/network/network_linux_test.go
  pkg/ocibundle/sif/bundle_linux.go
  pkg/ocibundle/sif/bundle_linux_test.go
  pkg/ocibundle/tools/overlay_linux.go
Labels: MacOS, Release 3.2.0, Testing

#2908 Fix Fatal CI Error
  cmd/internal/cli/singularity.go
Labels: Bug, Release 3.2.0

#2906 Add user-defined cflags to library checks
  mconfig
  mlocal/checks/project-post.chk
Labels: Bug, Release 3.1.1

#2885 Set PATH to default before action commands, not main command
  cmd/internal/cli/actions.go
  cmd/internal/cli/instance_start_linux.go
  cmd/internal/cli/singularity.go
Labels: BehaviorChange, Release 3.2.0

#2914 Support SCS system-wide endpoint config
  cmd/internal/cli/remote.go
  internal/app/singularity/remote_list.go
  internal/app/singularity/remote_login.go
  internal/app/singularity/remote_status.go
  internal/app/singularity/remote_use.go
  internal/pkg/remote/remote.go
  internal/pkg/remote/remote_test.go
Labels: Release 3.2.0, SCS

#2889 Plugin loading
  cmd/internal/cli/plugin_compile_linux.go
  cmd/internal/cli/singularity.go
  internal/app/singularity/plugin_compile_linux.go
  internal/pkg/buildcfg/confgen/gen.go
  internal/pkg/plugin/binary.go
  internal/pkg/plugin/load.go
  mlocal/frags/build_cli.mk
Labels: Release 3.2.0

#2886 Confirm Key Generate Password
  pkg/sypgp/sypgp.go
Labels: CLI, Enhancement, Release 3.2.0

#2916 Ask to Push Key After Generating a New Pair
  cmd/internal/cli/key.go
  cmd/internal/cli/key_newpair.go
  cmd/internal/cli/key_pull.go
  cmd/internal/cli/key_push.go
  cmd/internal/cli/key_search.go
  cmd/internal/cli/sign.go
  cmd/internal/cli/verify.go
  pkg/signing/signing.go
  pkg/sypgp/sypgp.go
Labels: CLI, Enhancement, Release 3.2.0

#2963 Remove duplicate KeysCmd code and use Aliases instead
  cmd/internal/cli/key.go
  docs/content.go
Labels: Release 3.2.0, TechnicalDebt

#3044 Adds detection for invalid URI transports
  cmd/internal/cli/pull.go
  internal/pkg/util/uri/uri.go
Labels: Enhancement

#3022 Read link from main thread (2967)
  internal/pkg/runtime/engines/singularity/container_linux.go
Labels: Bug, Release 3.1.1

#3023 Change directory from main thread with sandbox images (2978)
  internal/pkg/runtime/engines/singularity/prepare_linux.go
  internal/pkg/util/mainthread/mainthread.go
Labels: Bug, Release 3.1.1

#2976 Split CircleCI workflow into integration/unit tests
  .circleci/config.yml
  mlocal/frags/Makefile.stub
Labels: Performance, Testing

#3067 Update cobra vendor dependency
  Gopkg.lock
  vendor/github.com/spf13/cobra/.travis.yml
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/args.go
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/bash_completions.md
  vendor/github.com/spf13/cobra/cobra.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/command_win.go
  vendor/github.com/spf13/cobra/doc/man_docs.go
  vendor/github.com/spf13/cobra/go.mod
  vendor/github.com/spf13/cobra/go.sum
Labels: Release 3.1.1, Urgent

#3068 Fix instance list help typo
  docs/content.go
Labels: CLI, Release 3.1.1

#3069 Change message when no help is present
  cmd/internal/cli/run_help_linux.go
Labels: Documentation

#3070 Refactor singularity help run-help text
  cmd/internal/cli/run_help_linux.go
  docs/content.go
Labels: Documentation

#3074 Add user-defined cflags to library checks (2906-cherry-pick)
  mconfig
  mlocal/checks/project-post.chk
Labels: CherryPick

#3079 Remove `Y/n` When Searching for Keys
  docs/content.go
  pkg/sypgp/sypgp.go
Labels: CLI, Release 3.2.0

#3081 Do remote build when builder flag is set (3028 cherry-pick)
  cmd/internal/cli/build.go
  cmd/internal/cli/build_darwin.go
  cmd/internal/cli/build_linux.go
Labels: CherryPick

#3076 Fix RPM spec building on SLES 11 (2942 cherry-pick)
  dist/rpm/singularity.spec.in
Labels: CherryPick

#3085 Gv/2938 (2958 cherry pick)
  CONTRIBUTORS.md
  cmd/internal/cli/cache_clean_linux.go
Labels: CherryPick

#3110 Check container state during oci attach
  internal/app/singularity/oci_attach_linux.go
Labels: Bug, CherryPick, Release 3.1.1

#3109 Fix oci mount overlay directory deletion in case of failure
  pkg/ocibundle/tools/overlay_linux.go
Labels: Bug, CherryPick, Release 3.1.1

#3114 Fix oci pause/resume command
  internal/app/singularity/oci_exec_linux.go
  internal/app/singularity/oci_linux.go
  internal/app/singularity/oci_pause_linux.go
  internal/pkg/runtime/engines/oci/create_linux.go
  internal/pkg/runtime/engines/oci/prepare_linux.go
  internal/pkg/runtime/engines/oci/process_linux.go
  pkg/ociruntime/ociruntime.go
Labels: Bug, CherryPick, Release 3.1.1

#3128 Improve oci create error messages
  internal/app/singularity/oci_create_linux.go
Labels: CLI, CherryPick, Release 3.1.1

#3129 Add sub directory notion for instance helpers
  cmd/internal/cli/actions_linux.go
  cmd/internal/cli/instance_linux.go
  internal/app/singularity/oci_delete_linux.go
  internal/app/singularity/oci_linux.go
  internal/app/singularity/oci_run_linux.go
  internal/pkg/instance/instance_linux.go
  internal/pkg/runtime/engines/oci/cleanup_linux.go
  internal/pkg/runtime/engines/oci/create_linux.go
  internal/pkg/runtime/engines/oci/process_linux.go
  internal/pkg/runtime/engines/singularity/cleanup_linux.go
  internal/pkg/runtime/engines/singularity/prepare_linux.go
  internal/pkg/runtime/engines/singularity/process_linux.go
Labels: Bug, CherryPick, Release 3.1.1

#3121 Update the message shown when oci start is run on a container without a state of created
  internal/app/singularity/oci_start_linux.go
Labels: CLI, CherryPick, Release 3.1.1

#3120 Update the message shown when oci delete is run on a container without a state of created or stopped
  internal/app/singularity/oci_delete_linux.go
Labels: CLI, CherryPick, Release 3.1.1

#3119 Update the message shown when oci kill is run on a container without a state of created or running
  internal/app/singularity/oci_kill_linux.go
Labels: CLI, CherryPick, Release 3.1.1

#3082 Read link from main thread (3022 cherry-pick)
  internal/pkg/runtime/engines/singularity/container.go
Labels: CherryPick

#3072 Document blobSum type cache option
  cmd/internal/cli/cache_list_linux.go
  docs/content.go
Labels: CLI, CherryPick, Release 3.1.1

#3084 Improve package test coverage (build/types/parser)
  pkg/build/types/parser/deffile.go
  pkg/build/types/parser/deffile_test.go
Labels: Enhancement, Release 3.2.0, Testing

#3075 check for existing file before building docker based continer during …
  cmd/internal/cli/pull.go
Labels: CherryPick

#3066 Capability command fixes
  cmd/internal/cli/capability_add_linux.go
  cmd/internal/cli/capability_avail_linux.go
  cmd/internal/cli/capability_drop_linux.go
  cmd/internal/cli/capability_linux.go
  cmd/internal/cli/capability_list_linux.go
  docs/content.go
  internal/app/singularity/capability_avail_linux.go
  internal/app/singularity/capability_list_linux.go
  internal/app/singularity/capability_manage_linux.go
  pkg/util/capabilities/capabilities.go
Labels: Bug, CherryPick, Release 3.1.1

#3077 Use PACKAGE_NAME in --version output (2990 cherry-pick)
  cmd/internal/cli/singularity.go
Labels: CherryPick

#3083 Change directory from main thread with sandbox images (3023 cherry pick)
  internal/pkg/runtime/engines/singularity/prepare.go
  internal/pkg/util/mainthread/mainthread.go
Labels: CherryPick

#3086 Fix start.c error message typo (2920 cherry-pick)
  cmd/starter/c/starter.c
Labels: CherryPick

#3087 Fix instance list help typo (3068 cherry pick)
  docs/content.go
Labels: CherryPick

#3088 Change message when no help is present (3069 cherry pick)
  cmd/internal/cli/run_help_linux.go
Labels: CherryPick

#3090 Refactor singularity help run-help text (3070 cherry pick)
  cmd/internal/cli/run_help_linux.go
  docs/content.go
Labels: CherryPick

#3091 fixes #2927; refactor singularity commands test (2962 cherry pick)
  cmd/internal/cli/apps_linux.go
  cmd/internal/cli/singularity.go
  docs/content.go
Labels: CherryPick

#3080 Print Full Fingerprint When Verifying a Container
  pkg/signing/signing.go
Labels: Enhancement, Release 3.2.0

#3145 Check container state before attach (3110 cherry pick)
  internal/app/singularity/oci_attach_linux.go
Labels: CherryPick

#3146 Fix overlay directory not deleted caused by defer evaluation (3109 cherry pick)
  pkg/ocibundle/tools/overlay.go
Labels: CherryPick

#3147 Fix oci pause/resume command (3114 cherry pick)
  internal/app/singularity/oci_exec_linux.go
  internal/app/singularity/oci_linux.go
  internal/app/singularity/oci_pause_linux.go
  internal/pkg/runtime/engines/oci/create.go
  internal/pkg/runtime/engines/oci/prepare.go
  internal/pkg/runtime/engines/oci/process.go
  pkg/ociruntime/ociruntime.go
Labels: CherryPick

#3148 Improve oci create error messages (3128 cherry pick)
  internal/app/singularity/oci_create_linux.go
Labels: CherryPick

#3150 Update the message shown when oci start is run on a container without…
  internal/app/singularity/oci_start_linux.go
Labels: CherryPick

#3151 Update the message shown when oci delete is run on a container withou…
  internal/app/singularity/oci_delete_linux.go
Labels: CherryPick

#3152 Update the message shown when oci kill is run on a container without …
  internal/app/singularity/oci_kill_linux.go
Labels: CherryPick

#3154 Document blobSum type cache option (3072 cherry pick)
  cmd/internal/cli/cache_list_linux.go
  docs/content.go
Labels: CherryPick

#3155 Capability command fixes (3066 cherry pick)
  cmd/internal/cli/capability_add_linux.go
  cmd/internal/cli/capability_avail_linux.go
  cmd/internal/cli/capability_drop_linux.go
  cmd/internal/cli/capability_linux.go
  cmd/internal/cli/capability_list_linux.go
  docs/content.go
  internal/app/singularity/capability_avail_linux.go
  internal/app/singularity/capability_list_linux.go
  internal/app/singularity/capability_manage_linux.go
  pkg/util/capabilities/capabilities.go
Labels: CherryPick

#3140 Remove all subcommand in short use helps
  docs/content.go
Labels: CLI, CherryPick, Release 3.1.1

#3141 Store temporary sandbox image in /tmp for user namesapce + URI image
  cmd/internal/cli/actions_linux.go
Labels: Bug, CherryPick, Release 3.1.1

#3149 Add sub directory notion for instance helpers (3129 cherry pick)
  cmd/internal/cli/actions_linux.go
  cmd/internal/cli/instance_linux.go
  internal/app/singularity/oci_delete_linux.go
  internal/app/singularity/oci_linux.go
  internal/app/singularity/oci_run_linux.go
  internal/pkg/instance/instance.go
  internal/pkg/runtime/engines/oci/cleanup.go
  internal/pkg/runtime/engines/oci/create.go
  internal/pkg/runtime/engines/oci/process.go
  internal/pkg/runtime/engines/singularity/cleanup.go
  internal/pkg/runtime/engines/singularity/prepare.go
  internal/pkg/runtime/engines/singularity/process.go
Labels: CherryPick

#3160 Remove all subcommand in short use helps (3140 cherry pick)
  docs/content.go
Labels: CherryPick

#3161 Store temporary image in /tmp instead of HOME/.singularity/cache for …
  cmd/internal/cli/actions_linux.go
Labels: CherryPick

#3130 Clarify confusing rpm build instructions
  INSTALL.md
Labels: Documentation, Release 3.2.0

#3047 'key remove' Command
  cmd/internal/cli/key.go
  cmd/internal/cli/key_remove.go
  docs/content.go
  pkg/sypgp/sypgp.go
Labels: CLI, Release 3.2.0

#3172 Add sif convert info messages to 3.1.1 (cherry-pick of #2955)
  cmd/internal/cli/actions_linux.go
  internal/pkg/runtime/engines/singularity/cleanup.go
Labels: Release 3.1.1

#3056 Implement plugin inspect command
  cmd/internal/cli/plugin_inspect_linux.go
  cmd/internal/cli/plugin_linux.go
  docs/plugin.go
  internal/app/singularity/plugin_inspect_linux.go
  internal/pkg/plugin/binary.go
Labels: Release 3.2.0

#2919 Improved Cache List Output Summery
  cmd/internal/cli/cache_clean_linux.go
  cmd/internal/cli/cache_list_linux.go
  internal/app/singularity/cache_list_linux.go
Labels: Enhancement, Release 3.2.0
