Repository hpcng/singularity, pull requests merged in 2019-11, with the labels that each got.

#4692 Fix PROMPT_COMMAND evaluation issue
  etc/actions/exec
  etc/actions/run
  etc/actions/shell
Labels: Bug, Release 3.5

#4698 Fix current working directory symlink issue
  internal/pkg/runtime/engine/singularity/container_linux.go
  internal/pkg/util/fs/layout/manager.go
Labels: Bug, Regression, ci:e2e

#4704 Fix container mount destination containing symlink
  e2e/actions/actions.go
  e2e/testdata/Singularity
  internal/pkg/util/fs/helper.go
  internal/pkg/util/fs/helper_linux_test.go
  internal/pkg/util/fs/layout/layer/overlay/overlay_linux.go
  internal/pkg/util/fs/layout/layer/underlay/underlay_linux.go
Labels: Bug, Release 3.5, ci:e2e

#4728 Change '--groupid' to '--group-id' to match '--sif-id'
  CHANGELOG.md
  cmd/internal/cli/sign.go
  cmd/internal/cli/verify.go
  e2e/sign/sign.go
  e2e/verify/verify.go
Labels: CLI, CryptoSignatures

#4726 CLI cleanup for sign/verify
  cmd/internal/cli/sign.go
  cmd/internal/cli/verify.go
Labels: CryptoSignatures, Enhancement, ci:e2e

#4693 Fix missing STKFLT signal for mips
  internal/pkg/util/signal/signal_linux.go
  internal/pkg/util/signal/signal_linux_test.go
Labels: Bug, Packaging, TechnicalDebt

#4720 Override SIGABRT Go handler
  e2e/actions/actions.go
  e2e/internal/e2e/singularitycmd.go
  internal/app/starter/master_linux.go
  internal/pkg/util/signal/signal_linux.go
Labels: Bug, Runtime

#4742 Fix F_SETLK64 bad value on ppc64 arch with fcntl syscall
  pkg/util/fs/lock/const.go
  pkg/util/fs/lock/const_linux_32bit.go
Labels: Bug, Runtime

#4743 Wrap inspect command around singularity exec
  cmd/internal/cli/inspect_linux.go
Labels: Bug, Runtime, ci:e2e

#4753 Fix x86/arm/mips 32 bits system compilation error
  pkg/util/fs/lock/const.go
Labels: Regression, Release 3.5

#4746 Show explicit error for wrong unprivileged installation
  cmd/starter/c/starter.c
Labels: Enhancement, Runtime

#4747 Removed useless '--url' flag for sign
  CHANGELOG.md
  cmd/internal/cli/sign.go
Labels: CLI

#4754 Fix wrong st_dev/mountinfo for btrfs filesystem
  pkg/util/fs/proc/proc.go
Labels: Bug, Release 3.5, Runtime

#4744 Save/restore stack size limit with setuid workflow
  cmd/internal/cli/actions_linux.go
  internal/pkg/runtime/engine/singularity/process_linux.go
Labels: Bug, Runtime

#4626 [E2E] Add some umask tests for 'pull'
  e2e/pull/pull.go
Labels: Testing, e2e

#4752 Set default umask during stages build
  internal/pkg/build/build.go
Labels: Bug, ImageBuilding, Regression, Release 3.5, ci:e2e

#4761 Add allow container encrypted directive
  internal/pkg/runtime/engine/singularity/prepare_linux.go
  pkg/runtime/engine/config/config.go
Labels: Bug, Release 3.5, Runtime

#4759 Fix underlay/override directory issue
  e2e/actions/actions.go
  e2e/actions/regressions.go
  internal/pkg/runtime/engine/singularity/container_linux.go
  internal/pkg/util/fs/layout/layer/underlay/underlay_linux.go
  internal/pkg/util/fs/layout/manager.go
Labels: Bug, Regression, Release 3.5, Runtime

#4766 Fix index shift during optional fields parsing in parseMountInfoLine
  pkg/util/fs/proc/proc.go
  pkg/util/fs/proc/proc_linux_test.go
Labels: Bug, Release 3.5, Runtime

#4770 Fix current working directory symlink issue
  e2e/actions/actions.go
  e2e/actions/regressions.go
  internal/pkg/runtime/engine/singularity/container_linux.go
Labels: Bug, Regression, Release 3.5, Runtime

#4772 Fix setLk build error ... again
  pkg/util/fs/lock/var.go
  pkg/util/fs/lock/var_linux_32bit.go
Labels: Bug, Release 3.5

#4773 Check all partitions for image type check
  internal/pkg/runtime/engine/singularity/prepare_linux.go
Labels: Bug, Release 3.5, Runtime, ci:e2e

#4635 Add automatic detection of architecture during SIF assembler
  internal/pkg/build/assemblers/sif.go
  internal/pkg/runtime/engine/singularity/process_linux.go
  internal/pkg/util/machine/machine.go
  pkg/image/sif.go
Labels: Bug, ImageBuilding

#4777 Use temporary file to execute build script section
  internal/pkg/runtime/engine/imgbuild/create_linux.go
Labels: Bug, ImageBuilding, Release 3.5, ci:e2e

#4784 Cherry pick #4761, #4773 to release-3.5
  internal/pkg/runtime/engine/singularity/prepare_linux.go
  pkg/runtime/engine/config/config.go
Labels: ci:e2e

#4786 Cherry pick #4759,#4770 to release-3.5
  e2e/actions/actions.go
  e2e/actions/regressions.go
  internal/pkg/runtime/engine/singularity/container_linux.go
  internal/pkg/util/fs/layout/layer/underlay/underlay_linux.go
  internal/pkg/util/fs/layout/manager.go
Labels: ci:e2e

#4787 Cherry pick #4737 to release-3.5
  internal/pkg/client/oci/oci.go
Labels: ci:e2e

#4790 Cherry pick #4745,#4752,#4777 to release-3.5
  internal/pkg/build/build.go
  internal/pkg/runtime/engine/imgbuild/create_linux.go
  pkg/build/types/definition.go
Labels: ci:e2e

#4785 Add root filesystem escape checks
  cmd/starter/c/starter.c
Labels: Enhancement, Runtime, ci:e2e

#4796 Small Hotfix for Issue 2860 - All files in container owned by root
  internal/pkg/build/sources/packer_ext3_linux.go
  internal/pkg/build/sources/packer_sandbox.go
Labels: Bug, ImageBuilding, Release 3.5

#4802 Use errors=remount-ro mount option with ext3 filesystems only
  internal/pkg/runtime/engine/imgbuild/create_linux.go
  internal/pkg/util/fs/mount/mount_linux.go
  pkg/ocibundle/sif/bundle_linux.go
Labels: Bug, Release 3.5, Runtime

#4800 Fix underlay bind issue when the destination is a symlink
  e2e/actions/actions.go
  e2e/actions/regressions.go
  e2e/testdata/Singularity
  internal/pkg/util/fs/layout/layer/underlay/underlay_linux.go
Labels: Bug, Release 3.5, Runtime

#4803 Fix wrong path while joining shell path
  internal/pkg/util/machine/machine.go
Labels: Bug, ImageBuilding

#4806 Merge 3.5.1 rc.1 to master
  CHANGELOG.md
  INSTALL.md
  README.md
  e2e/actions/actions.go
  e2e/actions/regressions.go
  e2e/testdata/Singularity
  internal/pkg/runtime/engine/imgbuild/create_linux.go
  internal/pkg/util/fs/layout/layer/underlay/underlay_linux.go
  internal/pkg/util/fs/mount/mount_linux.go
  pkg/ocibundle/sif/bundle_linux.go
Labels: ci:e2e

#4771 Slightly improve help for sign/verify
  cmd/internal/cli/sign.go
  cmd/internal/cli/verify.go
Labels: CLI, CryptoSignatures
