Repository hpcng/singularity, pull requests merged in 2019-07, with the labels that each got.

#3737 E2E testing for 'inspect'
  e2e/inspect/inspect.go
  e2e/suite.go
  e2e/testdata/inspecter_container.def
  e2e/testdata/inspecter_container.sif
  go.mod
  go.sum
  vendor/github.com/buger/jsonparser/.gitignore
  vendor/github.com/buger/jsonparser/.travis.yml
  vendor/github.com/buger/jsonparser/Dockerfile
  vendor/github.com/buger/jsonparser/LICENSE
  vendor/github.com/buger/jsonparser/Makefile
  vendor/github.com/buger/jsonparser/README.md
  vendor/github.com/buger/jsonparser/bytes.go
  vendor/github.com/buger/jsonparser/bytes_safe.go
  vendor/github.com/buger/jsonparser/bytes_unsafe.go
  vendor/github.com/buger/jsonparser/escape.go
  vendor/github.com/buger/jsonparser/parser.go
  vendor/modules.txt
Labels: Release 3.4, Testing, e2e

#3798 Fix test coverage issue for internal/pkg/sylog
  internal/pkg/sylog/sylog.go
  internal/pkg/sylog/sylog_dummy_test.go
  internal/pkg/sylog/sylog_test.go
Labels: Testing

#3856 Remove the non-e2e privilege handling package.
  e2e/inspect/inspect.go
Labels: e2e

#3854 Add script to run e2e tests
  mlocal/frags/Makefile.stub
  scripts/e2e-test
Labels: e2e

#3803 Fix user namespace bind source located on a read-only filesystem
  internal/pkg/runtime/engines/singularity/container_linux.go
Labels: Bug, CherryPick, Regression, Release 3.3.0, Runtime

#3853 Pass test environment information as function arguments
  e2e/actions/actions.go
  e2e/docker/docker.go
  e2e/env/env.go
  e2e/help/help.go
  e2e/imgbuild/imgbuild.go
  e2e/inspect/inspect.go
  e2e/instance/instance.go
  e2e/instance/instance_utils.go
  e2e/internal/e2e/docker.go
  e2e/internal/e2e/env.go
  e2e/internal/e2e/image.go
  e2e/internal/e2e/imagepush.go
  e2e/pull/pull.go
  e2e/push/push.go
  e2e/remote/remote.go
  e2e/suite.go
  e2e/version/version.go
  go.mod
  vendor/github.com/kelseyhightower/envconfig/.travis.yml
  vendor/github.com/kelseyhightower/envconfig/LICENSE
  vendor/github.com/kelseyhightower/envconfig/MAINTAINERS
  vendor/github.com/kelseyhightower/envconfig/README.md
  vendor/github.com/kelseyhightower/envconfig/doc.go
  vendor/github.com/kelseyhightower/envconfig/env_os.go
  vendor/github.com/kelseyhightower/envconfig/env_syscall.go
  vendor/github.com/kelseyhightower/envconfig/envconfig.go
  vendor/github.com/kelseyhightower/envconfig/usage.go
  vendor/modules.txt
Labels: e2e

#3875 Changed SINGULARITY_NAME => SINGULARITY_PULL_NAME
  cmd/internal/cli/pull.go
Labels: BehaviorChange, Bug, CLI, CherryPick

#3705 Improve testing on pkg/sypgp.go
  pkg/sypgp/sypgp.go
  pkg/sypgp/sypgp_test.go
Labels: Testing

#3882 Add the `no_output_timeout` option to the `Run E2E tests` step in the `e2e_tests` job
  .circleci/config.yml
Labels: ContinuousIntegration, e2e

#3839 Port e2e docker tests to use new singularity execution context
  e2e/docker/docker.go
Labels: Enhancement, Testing, e2e

#3889 Fixed panic when export-ing a key when keyring is empty
  pkg/sypgp/sypgp.go
Labels: Bug, CherryPick, Release 3.3.0

#3890 Skip e2e tests for pull requests based on their changes
  .circleci/config.yml
Labels: ContinuousIntegration, e2e

#3878 Added 'cryptsetup' on install section
  INSTALL.md
Labels: Documentation

#3897 Build a sif from a sif without root
  cmd/internal/cli/build_linux.go
  internal/pkg/build/build.go
Labels: Bug, CherryPick, Release 3.3.0

#3793 Filter all unauthorized capabilities after user/group checks
  internal/pkg/runtime/engines/singularity/prepare_linux.go
Labels: Bug, Release 3.4, Runtime

#3864 Fs helper for temporary files and directories
  cmd/singularity/build_test.go
  cmd/singularity/pull_test.go
  e2e/docker/docker.go
  e2e/internal/e2e/fileutil.go
  internal/pkg/build/assemblers/assembler_sandbox_test.go
  internal/pkg/build/assemblers/assembler_sif_test.go
  internal/pkg/build/sources/conveyorPacker_oci_test.go
  internal/pkg/test/cache.go
  internal/pkg/test/tool/cache/cache.go
  internal/pkg/test/tool/doc.go
  internal/pkg/util/fs/helper.go
  internal/pkg/util/fs/helper_linux_test.go
  pkg/image/image_test.go
  pkg/ocibundle/sif/bundle_linux_test.go
Labels: Release 3.4, TechnicalDebt

#3868 Add some "Require" test helpers
  internal/pkg/test/tool/require/require.go
Labels: Enhancement, Release 3.4, Testing, e2e

#3896 Improving the output/workflow of 'verify' and 'pull'
  cmd/internal/cli/pull.go
  cmd/internal/cli/verify.go
  cmd/singularity/pull_test.go
  docs/content.go
  go.mod
  go.sum
  internal/app/singularity/pull.go
  pkg/signing/signing.go
  vendor/github.com/fatih/color/.travis.yml
  vendor/github.com/fatih/color/Gopkg.lock
  vendor/github.com/fatih/color/Gopkg.toml
  vendor/github.com/fatih/color/LICENSE.md
  vendor/github.com/fatih/color/README.md
  vendor/github.com/fatih/color/color.go
  vendor/github.com/fatih/color/doc.go
  vendor/github.com/mattn/go-colorable/.travis.yml
  vendor/github.com/mattn/go-colorable/LICENSE
  vendor/github.com/mattn/go-colorable/README.md
  vendor/github.com/mattn/go-colorable/colorable_appengine.go
  vendor/github.com/mattn/go-colorable/colorable_others.go
  vendor/github.com/mattn/go-colorable/colorable_windows.go
  vendor/github.com/mattn/go-colorable/go.mod
  vendor/github.com/mattn/go-colorable/go.sum
  vendor/github.com/mattn/go-colorable/noncolorable.go
  vendor/github.com/mattn/go-isatty/.travis.yml
  vendor/github.com/mattn/go-isatty/LICENSE
  vendor/github.com/mattn/go-isatty/README.md
  vendor/github.com/mattn/go-isatty/doc.go
  vendor/github.com/mattn/go-isatty/go.mod
  vendor/github.com/mattn/go-isatty/go.sum
  vendor/github.com/mattn/go-isatty/isatty_bsd.go
  vendor/github.com/mattn/go-isatty/isatty_linux.go
  vendor/github.com/mattn/go-isatty/isatty_others.go
  vendor/github.com/mattn/go-isatty/isatty_solaris.go
  vendor/github.com/mattn/go-isatty/isatty_windows.go
  vendor/modules.txt
Labels: CLI, Enhancement, Release 3.4

#3907 Remove the compare-url orb and replace it with a git command
  .circleci/config.yml
Labels: ContinuousIntegration, WIP, e2e

#3903 Add some non-root build tests
  e2e/imgbuild/imgbuild.go
  e2e/testdata/busybox.sif
Labels: ImageBuilding, Testing, e2e

#3826 Execute e2e tests inside their own pid and mount namespaces.
  e2e/e2e_test.go
  e2e/internal/e2e/docker.go
  e2e/internal/e2e/home.go
  e2e/internal/e2e/home_linux.go
  e2e/internal/e2e/init/init.go
  e2e/internal/e2e/init/init_linux.go
  e2e/internal/e2e/priv.go
  e2e/internal/e2e/priv_linux.go
  e2e/internal/e2e/user.go
  e2e/remote/remote.go
  e2e/suite.go
  e2e/testdata/Docker_registry.def
  mlocal/checks/project-post.chk
Labels: Enhancement, Testing, e2e

#3911 e2e: add match type argument for ExpectOutput and ExpectError
  e2e/actions/actions.go
  e2e/internal/e2e/singularitycmd.go
Labels: Enhancement, Testing, e2e

#3910 e2e port tests related to version cmd
  e2e/version/version.go
Labels: Testing, e2e

#3914 Rework cgroups test helpers
  internal/pkg/test/tool/require/require.go
Labels: Testing

#3920 Json output for 'verify'
  cmd/internal/cli/verify.go
  internal/app/singularity/pull.go
  internal/app/singularity/push.go
  pkg/signing/signing.go
Labels: Release 3.4

#3926 Add a fakeroot engine for build
  cmd/internal/cli/build.go
  cmd/internal/cli/build_darwin.go
  cmd/internal/cli/build_linux.go
  internal/pkg/build/build.go
  internal/pkg/build/sources/conveyorPacker_yum.go
  internal/pkg/build/stage.go
  internal/pkg/fakeroot/fakeroot.go
  internal/pkg/runtime/engines/engines_linux.go
  internal/pkg/runtime/engines/fakeroot/config/config.go
  internal/pkg/runtime/engines/fakeroot/engine_linux.go
  internal/pkg/runtime/engines/imgbuild/create_linux.go
  internal/pkg/runtime/engines/imgbuild/engine_linux.go
  internal/pkg/runtime/engines/imgbuild/process_linux.go
  internal/pkg/runtime/engines/imgbuild/rpc/args.go
  internal/pkg/runtime/engines/imgbuild/rpc/client/client.go
  internal/pkg/runtime/engines/imgbuild/rpc/server/server_linux.go
  internal/pkg/security/seccomp/seccomp_linux.go
  internal/pkg/security/seccomp/seccomp_linux_test.go
  internal/pkg/security/seccomp/seccomp_unsupported.go
  internal/pkg/security/security.go
  pkg/build/types/bundle.go
Labels: Bug, ImageBuilding

#3913 Move internal/pkg/test/exec to internal/pkg/test/tool/exec
  e2e/actions/actions.go
  e2e/help/help.go
  e2e/internal/e2e/imageverify.go
  e2e/remote/remote.go
  internal/pkg/test/tool/exec/exec.go
Labels: Testing

#3893 e2e tests for OCI commands
  e2e/oci/oci.go
  e2e/suite.go
Labels: OCI, Testing, e2e

#3933 Improving the json output for 'verify'
  pkg/signing/signing.go
Labels: Enhancement, Release 3.4

#3789 Remove the incomplete-downloaded cache if interrupted while pulling
  internal/app/singularity/interrupt_cleanup.go
  internal/app/singularity/pull.go
  internal/pkg/client/cache/dir.go
  internal/pkg/client/cache/library.go
  internal/pkg/client/cache/oci.go
  internal/pkg/client/cache/oras.go
Labels: Bug, CherryPick, Release 3.3.0

#3943 Use newuidmap/newgidmap as fakeroot fallback
  cmd/internal/cli/actions_linux.go
  cmd/internal/cli/build.go
  cmd/internal/cli/build_linux.go
  cmd/starter/c/include/starter.h
  cmd/starter/c/starter.c
  internal/pkg/fakeroot/fakeroot.go
  internal/pkg/fakeroot/fakeroot_test.go
  internal/pkg/instance/instance_linux.go
  internal/pkg/runtime/engines/config/starter/starter_linux.go
  internal/pkg/runtime/engines/fakeroot/engine_linux.go
  internal/pkg/runtime/engines/singularity/container_linux.go
  internal/pkg/runtime/engines/singularity/prepare_linux.go
  internal/pkg/runtime/engines/singularity/process_linux.go
  internal/pkg/util/user/identity.go
  internal/pkg/util/user/identity_test.go
  mlocal/checks/project-post.chk
  pkg/runtime/engines/singularity/config/config.go
  pkg/runtime/engines/singularity/config/data/singularity.conf
  pkg/util/namespaces/user_linux.go
  pkg/util/namespaces/user_unsupported.go
Labels: Bug, CherryPick, Enhancement, Release 3.3.0, Runtime

#3934 Verify E2E testing
  e2e/internal/e2e/image.go
  e2e/suite.go
  e2e/verify/verify.go
Labels: Release 3.4, Testing, e2e

#3953 Port E2E instance tests
  e2e/instance/instance.go
  e2e/instance/instance_utils.go
  e2e/internal/e2e/docker.go
  e2e/internal/e2e/home.go
  e2e/internal/e2e/home_linux.go
  e2e/internal/e2e/singularitycmd.go
  e2e/suite.go
Labels: Testing, e2e

#3716 Improve integration into SUSE SLE
  CHANGELOG.md
  CONTRIBUTORS.md
  examples/sle/Singularity
  go.mod
  internal/pkg/build/sources/conveyorPacker_zypper.go
  internal/pkg/build/sources/conveyorPacker_zypper_test.go
  pkg/build/types/parser/deffile.go
  pkg/build/types/parser/deffile_test.go
  pkg/build/types/parser/testdata_good/zypper_sle/zypper
  pkg/build/types/parser/testdata_good/zypper_sle/zypper.json
  pkg/build/types/parser/testdata_good/zypper_sle/zypper_sections.json
  vendor/modules.txt
Labels: ImageBuilding

#3948 Fakeroot configuration package
  internal/pkg/fakeroot/fakeroot.go
  internal/pkg/fakeroot/fakeroot_test.go
Labels: Enhancement, Release 3.4

#3931 Compile only compatible engines for starter SUID binary
  cmd/starter/engines/fakeroot_linux.go
  cmd/starter/engines/imgbuild_linux.go
  cmd/starter/engines/oci_linux.go
  cmd/starter/engines/singularity_linux.go
  cmd/starter/main_linux.go
  internal/app/starter/master_linux.go
  internal/app/starter/rpc_linux.go
  internal/app/starter/stage_linux.go
  internal/pkg/runtime/engines/engine/engine_linux.go
  internal/pkg/runtime/engines/engines_linux.go
  internal/pkg/runtime/engines/fakeroot/engine_linux.go
  internal/pkg/runtime/engines/imgbuild/engine_linux.go
  internal/pkg/runtime/engines/oci/engine_linux.go
  internal/pkg/runtime/engines/singularity/engine_linux.go
  internal/pkg/runtime/engines/singularity/monitor_linux.go
  internal/pkg/runtime/engines/singularity/plugins_linux.go
  mlocal/frags/build_network.mk
  mlocal/frags/build_runtime_suid.mk
  mlocal/frags/go_appsec_opts.mk
  mlocal/frags/go_common_opts.mk
  mlocal/frags/go_unix_opts.mk
Labels: Release 3.4, Runtime, TechnicalDebt

#3999 Remove copy/paste oversight in fakeroot engine
  internal/pkg/runtime/engines/fakeroot/engine_linux.go
Labels: Release 3.4, Runtime

#3603 Add 'SINGULARITY_DISABLE_CACHE'
  cmd/internal/cli/action_flags.go
  cmd/internal/cli/actions.go
  cmd/internal/cli/actions_linux.go
  cmd/internal/cli/build.go
  cmd/internal/cli/build_linux.go
  cmd/internal/cli/pull.go
  internal/app/singularity/pull.go
  internal/pkg/build/build.go
  internal/pkg/build/sources/conveyorPacker_library.go
  internal/pkg/build/sources/conveyorPacker_oci.go
  internal/pkg/build/sources/conveyorPacker_shub.go
  pkg/build/types/bundle.go
Labels: Enhancement, ImageBuilding, Release 3.4

#3970 Fix --contain issues. Fix bind destination creation
  internal/pkg/runtime/engines/imgbuild/create_linux.go
  internal/pkg/runtime/engines/oci/create_linux.go
  internal/pkg/runtime/engines/singularity/container_linux.go
  internal/pkg/runtime/engines/singularity/rpc/client/client.go
  internal/pkg/runtime/engines/singularity/rpc/server/server_linux.go
  internal/pkg/util/fs/layout/layer/overlay/overlay_linux.go
  internal/pkg/util/fs/layout/layer/underlay/underlay_linux.go
  internal/pkg/util/fs/layout/manager.go
  internal/pkg/util/fs/layout/session_linux.go
Labels: Bug, Enhancement, Release 3.4, Runtime

#4004 Update go to 1.12.7 in CI
  .circleci/config.yml
  cmd/starter/engines/engines.go
Labels: ContinuousIntegration

#4000 Update golangci-lint from 1.15.0 to 1.17.1
  mlocal/frags/Makefile.stub
Labels: ContinuousIntegration, Testing

#4001 [3.3] bug fix for building a sif without root
  cmd/internal/cli/build_linux.go
Labels: Bug, Release 3.3.0

#4006 Fix integer overflow on 32 bits system in fakeroot package
  internal/pkg/fakeroot/fakeroot.go
  internal/pkg/fakeroot/fakeroot_test.go
Labels: Bug, Release 3.4, Runtime

#4011 Port e2e inspect tests
  e2e/inspect/inspect.go
Labels: Testing, e2e

#4039 Cache Shub images by commit hash
  cmd/internal/cli/actions.go
  internal/app/singularity/pull.go
  internal/pkg/build/sources/conveyorPacker_shub.go
  pkg/client/shub/api.go
  pkg/client/shub/pull.go
  pkg/client/shub/pull_test.go
  pkg/client/shub/util.go
  pkg/client/shub/util_test.go
Labels: Bug, CherryPick, Release 3.3.0, Release 3.4

#4042 Fixed Shub URI issue (followup for #4039)
  cmd/internal/cli/actions.go
  internal/app/singularity/pull.go
  internal/pkg/build/sources/conveyorPacker_shub.go
Labels: Bug, CherryPick, Release 3.4

#4009 Check SIF squashfs/ext3 partitions at load time
  internal/pkg/runtime/engines/singularity/container_linux.go
  pkg/image/ext3.go
  pkg/image/image.go
  pkg/image/sandbox.go
  pkg/image/sif.go
  pkg/image/sif_test.go
  pkg/image/squashfs.go
Labels: Bug, Release 3.4, Runtime

#4051 Fix broken fork_ns on arm64 by allocating a larger stack
  cmd/starter/c/starter.c
Labels: Bug, Runtime

#4013 Show unsquashfs command failure output
  pkg/image/unpacker/squashfs.go
Labels: CLI, Enhancement

#4036 Add recursive mount flag for /tmp and /var/tmp in build engine
  internal/pkg/runtime/engines/imgbuild/create_linux.go
Labels: Bug, ImageBuilding

#4047 Fix fakeroot and SELinux issue
  internal/pkg/runtime/engines/fakeroot/engine_linux.go
Labels: Bug, Runtime

#4060 Fix cryptsetup hang when running from a container IPC namespace
  internal/pkg/runtime/engines/singularity/container_linux.go
  internal/pkg/runtime/engines/singularity/rpc/args.go
  internal/pkg/runtime/engines/singularity/rpc/client/client.go
  internal/pkg/runtime/engines/singularity/rpc/server/server_linux.go
Labels: Bug, Runtime

#4064 Include Go tags and Cgo files for go list in gengodep
  makeit/gengodep
  mlocal/frags/build_cli.mk
  mlocal/frags/build_runtime.mk
Labels: Bug

#4029 Fix port handling
  pkg/network/network_linux.go
  pkg/network/network_linux_test.go
Labels: CherryPick, Release 3.4

#4062 Fix scratch mount and remove false skipping mount warning
  internal/pkg/runtime/engines/singularity/container_linux.go
  internal/pkg/util/fs/layout/manager.go
Labels: Bug, Runtime

#4054 Change "Build complete: <target.sif>" to point to target (instead of cache)
  cmd/internal/cli/build_linux.go
  internal/app/singularity/pull.go
  internal/pkg/build/build.go
Labels: Enhancement, Release 3.4
