Repository hpcng/singularity, pull requests merged in 2019-09, with the labels that each got.

#4350 Add an e2e test for the buildcfg command
  e2e/buildcfg/buildcfg.go
  e2e/suite.go
Labels: Testing, e2e

#4353 Add test for the help flag for e2e remote tests
  e2e/remote/remote.go
Labels: Testing, e2e

#4359 Document runtime egines
  internal/pkg/runtime/engine/engine_linux.go
  internal/pkg/runtime/engine/fakeroot/engine_linux.go
  internal/pkg/runtime/engine/imgbuild/create_linux.go
  internal/pkg/runtime/engine/imgbuild/engine_linux.go
  internal/pkg/runtime/engine/imgbuild/process_linux.go
  internal/pkg/runtime/engine/oci/cleanup_linux.go
  internal/pkg/runtime/engine/oci/config_linux.go
  internal/pkg/runtime/engine/oci/create_linux.go
  internal/pkg/runtime/engine/oci/engine_linux.go
  internal/pkg/runtime/engine/oci/monitor_linux.go
  internal/pkg/runtime/engine/oci/prepare_linux.go
  internal/pkg/runtime/engine/oci/process_linux.go
  internal/pkg/runtime/engine/singularity/cleanup_linux.go
  internal/pkg/runtime/engine/singularity/container_linux.go
  internal/pkg/runtime/engine/singularity/create_linux.go
  internal/pkg/runtime/engine/singularity/engine_linux.go
  internal/pkg/runtime/engine/singularity/monitor_linux.go
  internal/pkg/runtime/engine/singularity/prepare_linux.go
  internal/pkg/runtime/engine/singularity/process_linux.go
  internal/pkg/runtime/engine/singularity/rpc/server/server_linux.go
  internal/pkg/util/priv/priv_linux.go
  pkg/runtime/engines/singularity/config/config.go
Labels: Documentation, Runtime, TechnicalDebt

#4380 Fix FuseMount check causing to always set PID namespace
  cmd/internal/cli/actions_linux.go
Labels: Bug, Regression

#4372 Delete ghost instance files
  e2e/instance/instance.go
  internal/app/singularity/oci_exec_linux.go
  internal/pkg/instance/instance_linux.go
  internal/pkg/instance/instance_linux_test.go
  pkg/util/fs/proc/proc.go
  pkg/util/fs/proc/proc_linux_test.go
Labels: Bug, Release 3.5

#4365 Rework overlay image loading code
  cmd/internal/cli/actions_linux.go
  cmd/singularity/actions_test.go
  cmd/starter/c/starter.c
  e2e/actions/actions.go
  e2e/internal/e2e/docker.go
  e2e/testdata/Docker_registry.def
  internal/pkg/runtime/engine/singularity/container_linux.go
  internal/pkg/runtime/engine/singularity/prepare_linux.go
  internal/pkg/runtime/engine/singularity/process_linux.go
  pkg/image/squashfs.go
  pkg/image/squashfs_test.go
  pkg/runtime/engines/singularity/config/config.go
Labels: Bug, Release 3.5

#4386 E2E: attempt to signed a non-existent groupID/ID
  e2e/sign/sign.go
  e2e/suite.go
Labels: Enhancement, Testing, e2e

#4409 Fix error when using sandbox path with slash at the end
  e2e/e2e.go
  e2e/imgbuild/imgbuild.go
  e2e/internal/e2e/imageverify.go
  internal/pkg/build/build.go
Labels: Bug

#4387 Fix fakeroot image cleanup permission denied and rework starter execution util
  cmd/internal/cli/actions_linux.go
  cmd/internal/cli/build_linux.go
  cmd/internal/cli/inspect_linux.go
  cmd/internal/cli/run_help_linux.go
  internal/app/singularity/oci_create_linux.go
  internal/app/singularity/oci_exec_linux.go
  internal/pkg/build/build.go
  internal/pkg/runtime/engine/fakeroot/config/config.go
  internal/pkg/runtime/engine/fakeroot/engine_linux.go
  internal/pkg/runtime/engine/singularity/cleanup_linux.go
  internal/pkg/util/exec/pipe_linux.go
  internal/pkg/util/exec/pipe_unsupported.go
  internal/pkg/util/starter/starter.go
  internal/pkg/util/starter/starter_linux.go
  internal/pkg/util/starter/starter_unsupported.go
Labels: Bug, Runtime

#4421 Improve e2e to use common fs helper function
  e2e/internal/e2e/fileutil.go
  e2e/internal/e2e/imageverify.go
  e2e/verify/verify.go
Labels: Enhancement, Release 3.5, e2e

#4436 Fix @chmod makefile error at install step
  mlocal/frags/build_runtime_suid.mk
Labels: Bug

#4411 Fix multiple bind issues
  cmd/internal/cli/actions_linux.go
  cmd/singularity/actions_test.go
  e2e/actions/actions.go
  internal/pkg/runtime/engine/fakeroot/engine_linux.go
  internal/pkg/runtime/engine/oci/create_linux.go
  internal/pkg/runtime/engine/singularity/container_linux.go
  internal/pkg/runtime/engine/singularity/prepare_linux.go
  internal/pkg/util/fs/mount/system_linux.go
  internal/pkg/util/fs/mount/system_linux_test.go
  pkg/runtime/engines/singularity/config/config.go
  pkg/util/fs/proc/proc.go
  pkg/util/fs/proc/proc_linux_test.go
Labels: Bug, Release 3.5, WIP

#4339 Fix fakeroot build with pacstrap and debootstrap
  internal/pkg/build/sources/conveyorPacker_arch.go
  internal/pkg/build/sources/conveyorPacker_arch_linux.go
  internal/pkg/build/sources/conveyorPacker_arch_unsupported.go
  internal/pkg/build/sources/conveyorPacker_debootstrap.go
  internal/pkg/build/sources/conveyorPacker_debootstrap_linux.go
  internal/pkg/build/sources/conveyorPacker_debootstrap_unsupported.go
Labels: Bug, ImageBuilding

#4427 Updated the --sif-id flag for E2E tests
  e2e/sign/sign.go
  e2e/verify/verify.go
Labels: Release 3.5, e2e

#4405 Add key import flag to specify if new pass needed
  cmd/internal/cli/key.go
  cmd/internal/cli/key_import.go
  pkg/sypgp/sypgp.go
Labels: CLI, Release 3.5

#4449 Fix ioctl errno handling for LOOP_SET_STATUS64
  CONTRIBUTORS.md
  pkg/util/loop/loop_linux.go
Labels: Bug, Runtime

#4473 Fix bind regression with sandbox and user namespace
  e2e/actions/actions.go
  internal/pkg/runtime/engine/singularity/container_linux.go
Labels: Bug, Regression

#4471 Remove tmp file from 'key newpair' tests
  cmd/internal/cli/key_newpair_test.go
Labels: Release 3.5, Testing

#4487 Fix regression breaking --net usage
  internal/pkg/runtime/engine/singularity/container_linux.go
Labels: Bug, Regression

#4497 Fix image file descriptor leak
  cmd/internal/cli/actions_linux.go
  e2e/actions/actions.go
  e2e/actions/regressions.go
Labels: Bug

#4451 Detect autofs path automatically and get rid of autofs bug path configuration
  etc/conf/testdata/test_1.out.correct
  etc/conf/testdata/test_2.in
  etc/conf/testdata/test_2.out.correct
  etc/conf/testdata/test_3.in
  etc/conf/testdata/test_3.out.correct
  etc/conf/testdata/test_default.tmpl
  internal/pkg/runtime/engine/singularity/prepare_linux.go
  pkg/runtime/engines/singularity/config/config.go
  pkg/runtime/engines/singularity/config/data/singularity.conf
Labels: Enhancement, Release 3.5

#4492 Added note in INSTALL.md to remove Go before updateing + bump go version
  INSTALL.md
Labels: Enhancement

#4493 Update to issue template
  .github/ISSUE_TEMPLATE.md
Labels: Enhancement

#4508 Add network e2e helper and few basic networking e2e tests
  e2e/actions/actions.go
  internal/pkg/test/tool/require/require.go
  internal/pkg/test/tool/require/require_linux.go
  internal/pkg/test/tool/require/require_unsupported.go
Labels: Testing, e2e

#4527 Fix a typo in the debug message in the plugin code
  internal/app/singularity/plugin_compile_linux.go
Labels: Plugin

#4514 Cleanup overlay e2e actions test
  e2e/actions/actions.go
Labels: Testing, e2e

#4535 Only try to connect to the keystore if we are pushing the key
  cmd/internal/cli/key_newpair.go
Labels: Bug, CLI

#4529 Return explicit error regarding build with sandbox/update flags
  cmd/internal/cli/build.go
  cmd/internal/cli/build_darwin.go
  cmd/internal/cli/build_linux.go
  e2e/imgbuild/imgbuild.go
Labels: CLI, Release 3.4
