Repository hpcng/singularity, pull requests merged in 2020-04, with the labels that each got.

#5151 Fix resolved path check error
  internal/pkg/runtime/engine/singularity/prepare_linux.go
Labels: ci:e2e

#5147 Rework sylog package
  cmd/internal/cli/singularity.go
  cmd/starter/c/include/message.h
  cmd/starter/c/message.c
  internal/pkg/build/sources/oci_unpack_linux.go
  internal/pkg/sylog/sylog.go
  internal/pkg/sylog/sylog_common.go
  internal/pkg/sylog/sylog_dummy.go
  internal/pkg/sylog/sylog_dummy_test.go
  internal/pkg/sylog/sylog_test.go
Labels: ci:e2e

#5164 Allow to specify a buildcfg parameter to get parameter value directly
  cmd/internal/cli/buildconfig.go
  e2e/buildcfg/buildcfg.go
Labels: Enhancement, ci:e2e

#5162 Fix user bind logic when binding devices from host /dev to container
  internal/pkg/runtime/engine/singularity/container_linux.go
Labels: Bug, Runtime, ci:e2e

#5165 Fix issue triggered when using a FUSE image driver/writable overlay/fakeroot
  internal/pkg/runtime/engine/singularity/container_linux.go
  internal/pkg/runtime/engine/singularity/rpc/args.go
  internal/pkg/runtime/engine/singularity/rpc/client/client.go
  internal/pkg/runtime/engine/singularity/rpc/server/server_linux.go
Labels: Bug, Runtime

#5179 Honor insecure registries in /etc/containers/registries.conf
  e2e/docker/docker.go
  e2e/imgbuild/imgbuild.go
  e2e/imgbuild/regressions.go
  internal/pkg/build/sources/conveyorPacker_oci.go
  internal/pkg/client/oci/pull.go
Labels: Bug, ci:e2e

#5180 Remove http_proxy environment variable handling from yum bootstrap
  internal/pkg/build/sources/conveyorPacker_yum.go
Labels: Bug, BuildIssue

#5182 Improve namespace error message in C starter code
  cmd/starter/c/starter.c
Labels: Enhancement, Runtime

#5187 Reduce warning showed when 'user bind control = no'
  internal/pkg/runtime/engine/singularity/container_linux.go
Labels: Runtime

#5204 Bump mvdan.cc/sh/v3 to 3.1.0
  go.mod
  go.sum
Labels: ci:e2e, dependencies

#5199 Remove setns compilation check and define custom setns wrapper
  cmd/starter/c/include/setns.h
  cmd/starter/c/setns.c
  cmd/starter/c/starter.c
  mlocal/checks/project-post.chk
Labels: BuildIssue

#5218 Use subcommand in usage messages after #5208
  cmd/internal/cli/singularity.go
Labels: ci:e2e

#5222 Handle correct public/private key check for build/actions
  cmd/internal/cli/build_linux.go
  pkg/util/crypt/key.go
Labels: ci:e2e

#5230 Don't attempt impossible home mount of '/'
  e2e/actions/actions.go
  e2e/actions/regressions.go
  internal/pkg/runtime/engine/singularity/container_linux.go
Labels: ci:e2e

#5232 Update CHANGELOG with more complete 3.5->3.6 changes
  CHANGELOG.md
Labels: Documentation

#5238 Testing: fix E2E test suite
  e2e/inspect/inspect.go
Labels: ci:e2e

#5237 Build: use buffered chan for signal notification
  internal/pkg/build/build.go
Labels: ci:e2e

#5233 Fix SIGURG Handling
  internal/app/starter/master_linux.go
  internal/pkg/runtime/engine/fakeroot/engine_linux.go
  internal/pkg/runtime/engine/oci/monitor_linux.go
  internal/pkg/runtime/engine/singularity/monitor_linux.go
  internal/pkg/runtime/engine/singularity/process_linux.go
Labels: ci:e2e

#5227 fix 5211: don't mount home when --fakeroot and --contain are given
  CONTRIBUTORS.md
  cmd/internal/cli/actions_linux.go
  e2e/actions/actions.go
  e2e/actions/regressions.go
  internal/pkg/runtime/engine/singularity/container_linux.go
Labels: ci:e2e

#5257 Update --fusemount help. Fixes #5255
  cmd/internal/cli/action_flags.go
Labels: Documentation
