Repository hpcng/singularity, pull requests merged in 2020-03, with the labels that each got.

#5070 Image driver fixes
  cmd/internal/cli/actions_linux.go
  cmd/starter/c/starter.c
  internal/pkg/runtime/engine/singularity/container_linux.go
Labels: Bug, Runtime, ci:e2e

#5083 Fix configuration parser regular expression to exclude newlines and carriage returns
  pkg/util/singularityconf/parser.go
Labels: Bug, ci:e2e

#5072 Remove singularity_source symlink in plugin examples
  e2e/plugin/testdata/cli/singularity_source
  e2e/plugin/testdata/runtime_singularity/singularity_source
  examples/plugins/cli-plugin/singularity_source
  examples/plugins/config-plugin/singularity_source
  examples/plugins/log-plugin/singularity_source
  examples/plugins/ubuntu-userns-overlay-plugin/singularity_source
Labels: ci:e2e

#5084 Image driver fixes/enhancements
  cmd/internal/cli/actions_linux.go
  examples/plugins/ubuntu-userns-overlay-plugin/main.go
  internal/pkg/runtime/engine/singularity/cleanup_linux.go
  internal/pkg/runtime/engine/singularity/container_linux.go
  internal/pkg/runtime/engine/singularity/prepare_linux.go
  pkg/util/singularityconf/config.go
Labels: Runtime, ci:e2e

#5100 Fix rootfs umount error with sandbox image and image driver
  internal/pkg/runtime/engine/singularity/cleanup_linux.go
Labels: Bug

#5104 Shell interpreter fixes
  internal/pkg/runtime/engine/singularity/process_linux.go
  internal/pkg/util/fs/files/action_scripts.go
Labels: ci:e2e

#5110 Wrap docker environment variable value with double quotes
  internal/pkg/build/sources/conveyorPacker_oci.go
Labels: Bug, ci:e2e

#5111 Add runtime plugin configuration
  pkg/runtime/engine/config/config.go
Labels: ci:e2e

#5107 Fix backslash escape with declaration builtin in shell interpreter
  internal/pkg/util/shell/interpreter/interpreter.go
Labels: ci:e2e

#5112 Image bind fixes
  internal/pkg/runtime/engine/singularity/container_linux.go
Labels: ci:e2e

#5114 Mimic CWD mount v2 behavior
  CHANGELOG.md
  internal/pkg/runtime/engine/singularity/container_linux.go
  internal/pkg/util/fs/mount/mount_linux.go
Labels: Bug, ci:e2e

#5119 Use image package for SIF plugin code
  internal/pkg/plugin/binary.go
  internal/pkg/plugin/meta.go
  internal/pkg/plugin/sif.go
  internal/pkg/plugin/sif_test.go
Labels: ci:e2e

#5117 Add VFS for session layer manager
  internal/pkg/runtime/engine/oci/create_linux.go
  internal/pkg/runtime/engine/oci/rpc/args.go
  internal/pkg/runtime/engine/oci/rpc/client/client.go
  internal/pkg/runtime/engine/oci/rpc/server/server_linux.go
  internal/pkg/runtime/engine/singularity/container_linux.go
  internal/pkg/runtime/engine/singularity/rpc/args.go
  internal/pkg/runtime/engine/singularity/rpc/client/client.go
  internal/pkg/runtime/engine/singularity/rpc/server/server_linux.go
  internal/pkg/util/fs/layout/layer/overlay/overlay_linux.go
  internal/pkg/util/fs/layout/layer/underlay/underlay_linux.go
  internal/pkg/util/fs/layout/manager.go
  internal/pkg/util/fs/layout/manager_test.go
  internal/pkg/util/fs/layout/session_linux.go
Labels: ci:e2e

#5126 Add e2e tests for --config global option
  e2e/config/config.go
Labels: Testing, ci:e2e

#5127 Fix configuration parser for empty slice and default value
  pkg/util/singularityconf/parser.go
Labels: ci:e2e

#5130 Rework/fix inspect command and expose metadata JSON structure as public package
  cmd/internal/cli/inspect.go
  cmd/internal/cli/inspect_darwin.go
  cmd/internal/cli/inspect_linux.go
  e2e/inspect/inspect.go
  e2e/testdata/inspecter_container.def
  pkg/inspect/metadata.go
Labels: Enhancement, ci:e2e

#5140 Bump umoci to commit with xattr error suppression
  go.mod
  go.sum
Labels: ci:e2e

#5122 Remove build engine
  CHANGELOG.md
  cmd/starter/engines/imgbuild_linux.go
  internal/pkg/build/build.go
  internal/pkg/build/stage.go
  internal/pkg/build/util.go
  internal/pkg/runtime/engine/imgbuild/config/config.go
  internal/pkg/runtime/engine/imgbuild/create_linux.go
  internal/pkg/runtime/engine/imgbuild/engine_linux.go
  internal/pkg/runtime/engine/imgbuild/process_linux.go
  mlocal/frags/go_common_opts.mk
  pkg/build/types/metadata.go
Labels: ci:e2e
