Repository hpcng/singularity, pull requests merged in 2020-01, with the labels that each got.

#4794 Generate Go dependencies for CLI/runtime
  .circleci/config.yml
  makeit/gengodep
  mconfig
  mlocal/frags/Makefile.stub
  mlocal/frags/build_cli.mk
  mlocal/frags/build_runtime.mk
  mlocal/frags/build_runtime_suid.mk
  mlocal/frags/build_scripts.mk
  mlocal/frags/go_common_opts.mk
  scripts/e2e-test
  scripts/go-test.in
  scripts/test-sudo
Labels: Packaging

#4922 Add ceph to filesystems needing st_dev workaround
  pkg/util/fs/proc/proc.go
Labels: Release 3.5

#4924 Fix CLI init() call order
  cmd/internal/cli/action_flags.go
  cmd/internal/cli/build.go
  cmd/internal/cli/buildconfig.go
  cmd/internal/cli/cache_clean_linux.go
  cmd/internal/cli/cache_linux.go
  cmd/internal/cli/cache_list_linux.go
  cmd/internal/cli/capability_linux.go
  cmd/internal/cli/config_fakeroot_linux.go
  cmd/internal/cli/config_global_linux.go
  cmd/internal/cli/config_linux.go
  cmd/internal/cli/delete.go
  cmd/internal/cli/inspect_darwin.go
  cmd/internal/cli/inspect_linux.go
  cmd/internal/cli/instance_linux.go
  cmd/internal/cli/instance_list_linux.go
  cmd/internal/cli/instance_start_linux.go
  cmd/internal/cli/instance_stop_linux.go
  cmd/internal/cli/key.go
  cmd/internal/cli/key_export.go
  cmd/internal/cli/key_list.go
  cmd/internal/cli/oci_linux.go
  cmd/internal/cli/plugin_compile_linux.go
  cmd/internal/cli/plugin_install_linux.go
  cmd/internal/cli/plugin_linux.go
  cmd/internal/cli/pull.go
  cmd/internal/cli/push.go
  cmd/internal/cli/remote.go
  cmd/internal/cli/run_help_linux.go
  cmd/internal/cli/search.go
  cmd/internal/cli/siftool.go
  cmd/internal/cli/sign.go
  cmd/internal/cli/singularity.go
  cmd/internal/cli/verify.go
Labels: CLI, TechnicalDebt, ci:e2e

#4875 Replace +dirty by -dirty to be compatible with semantic version
  scripts/get-version
Labels: Packaging, ci:e2e

#4926 Bind /etc/hosts or create a default one with --contain flag
  internal/pkg/runtime/engine/singularity/container_linux.go
  internal/pkg/util/fs/files/default_hosts.go
  pkg/runtime/engine/config/config.go
Labels: Bug, Runtime, ci:e2e

#4932 Fix regression in e2e coverage command introduced by 4924
  cmd/docs/cmds/cmdtree.go
  cmd/internal/cli/singularity.go
Labels: Bug, ci:e2e, e2e

#4935 Fix a logic error with sandbox image and all layers disabled
  internal/pkg/runtime/engine/singularity/prepare_linux.go
Labels: Bug, Regression, Runtime

#4946 Fix nvidia persitenced socket bind mount error with --writable
  cmd/internal/cli/actions_linux.go
Labels: Bug, Runtime

#4958 Ensure build rootPath has owner write permission
  e2e/regressions/build.go
  internal/pkg/build/sources/base_environment.go
Labels: Bug, ImageBuilding

#4959 Bump to 0.1.1 tagged mtrmac/gpgme
  go.mod
  go.sum
Labels: ci:e2e, dependencies

#4953 Cleanup FUSE code
  cmd/internal/cli/action_flags.go
  cmd/internal/cli/actions_linux.go
  cmd/starter/c/starter.c
  e2e/actions/actions.go
  e2e/internal/e2e/docker.go
  e2e/internal/e2e/home_linux.go
  e2e/testdata/sshfs.def
  internal/pkg/runtime/engine/singularity/cleanup_linux.go
  internal/pkg/runtime/engine/singularity/container_linux.go
  internal/pkg/runtime/engine/singularity/prepare_linux.go
  internal/pkg/runtime/engine/singularity/process_linux.go
  internal/pkg/runtime/engine/singularity/rpc/args.go
  internal/pkg/runtime/engine/singularity/rpc/client/client.go
  internal/pkg/runtime/engine/singularity/rpc/server/server_linux.go
  internal/pkg/util/env/clean.go
  pkg/runtime/engine/singularity/config/config.go
  pkg/runtime/engine/singularity/config/config_linux.go
Labels: ci:e2e

#4964 Fix e2e instance test race
  e2e/actions/actions.go
  e2e/instance/instance.go
  e2e/instance/instance_utils.go
  e2e/internal/e2e/docker.go
  e2e/internal/e2e/home_linux.go
  e2e/testdata/sshfs.def
Labels: Bug, ci:e2e, e2e

#4963 Fix CLI command root user check for unprivileged installation
  cmd/internal/cli/actions_linux.go
  cmd/internal/cli/config_fakeroot_linux.go
  cmd/internal/cli/config_global_linux.go
  cmd/internal/cli/oci_linux.go
  cmd/internal/cli/plugin_disable_linux.go
  cmd/internal/cli/plugin_enable_linux.go
  cmd/internal/cli/plugin_install_linux.go
  cmd/internal/cli/plugin_uninstall_linux.go
  cmd/internal/cli/singularity.go
  docs/content.go
Labels: Bug, CLI, ci:e2e

#4974 Add CAP_SYS_ADMIN check for root user and user namespace fallback
  cmd/internal/cli/actions_linux.go
  pkg/util/capabilities/process.go
  pkg/util/capabilities/process_test.go
Labels: Bug, CLI, ci:e2e

#4972 Fix build post/test -c section parameter regression
  e2e/regressions/build.go
  e2e/testdata/regressions/issue_4967.def
  internal/pkg/runtime/engine/imgbuild/create_linux.go
Labels: Bug, ImageBuilding, Regression

#4973 Fix build post section issue /etc/resolv.conf and/or /etc/hosts are missing
  e2e/regressions/build.go
  e2e/testdata/regressions/issue_4969.def
  internal/pkg/runtime/engine/imgbuild/create_linux.go
Labels: Bug, ImageBuilding

#4981 Update dependencies
  go.mod
  go.sum
  internal/pkg/runtime/engine/fakeroot/engine_linux.go
  internal/pkg/runtime/engine/imgbuild/engine_linux.go
  internal/pkg/runtime/engine/singularity/prepare_linux.go
  internal/pkg/runtime/engine/singularity/process_linux.go
Labels: ci:e2e, dependencies

#4980 Bump libseccomp-golang to v0.9.1
  e2e/oci/oci.go
  go.mod
  go.sum
  internal/pkg/runtime/engine/config/oci/config.go
  internal/pkg/runtime/engine/imgbuild/engine_linux.go
  internal/pkg/security/seccomp/seccomp_linux.go
  pkg/ocibundle/tools/oci.go
Labels: Runtime, ci:e2e, dependencies

#4982 Move to latest go mod versioned containers/image v5
  cmd/internal/cli/actions.go
  cmd/internal/cli/build.go
  cmd/internal/cli/singularity.go
  go.mod
  go.sum
  internal/app/singularity/pull.go
  internal/pkg/build/sources/conveyorPacker_oci.go
  internal/pkg/build/sources/oci_unpack_darwin.go
  internal/pkg/build/sources/oci_unpack_linux.go
  internal/pkg/client/oci/oci.go
  internal/pkg/client/oci/oci_test.go
  internal/pkg/client/oci/transports.go
  internal/pkg/client/oci/transports_test.go
  internal/pkg/oras/oras.go
  pkg/build/types/bundle.go
Labels: ci:e2e, dependencies

#4976 Automatically handle overlay read-only option based on filesystem
  e2e/actions/actions.go
  internal/pkg/runtime/engine/singularity/prepare_linux.go
  pkg/image/image.go
  pkg/image/squashfs.go
Labels: Regression, Runtime

#4988 Remove obsolete libuuid and libssl build checks
  .circleci/config.yml
  .travis.yml
  .travis/rpmbuild_test
  INSTALL.md
  dist/rpm/singularity.spec.in
  mlocal/checks/project-post.chk
Labels: ci:e2e
