Repository hpcng/singularity, pull requests merged in 2020-09, with the labels that each got.

#5548 Add CAP_MKNOD in capability bounding set of RPC
  cmd/starter/c/starter.c
Labels: Bug, Regression, ci:e2e

#5549 Fix decryption issue when using both IPC and PID namespaces
  e2e/run/run.go
  internal/pkg/runtime/engine/singularity/rpc/server/server_linux.go
Labels: Bug, ci:e2e

#5550 Fix unsupported builtins panic from shell interpreter and add umask support
  internal/pkg/runtime/engine/singularity/process_linux.go
  internal/pkg/util/fs/files/action_scripts.go
Labels: Bug, Regression, ci:e2e

#5562 fix: Do not load keyring in prepare_linux if ECL not enabled
  internal/pkg/runtime/engine/singularity/prepare_linux.go
Labels: ci:e2e

#5568 Ensure sandbox option overrides remote build dst
  cmd/internal/cli/build_linux.go
Labels: CLI, ImageBuilding, SCS
