Repository hpcng/singularity, pull requests merged in 2020-05, with the labels that each got.

#5272 Fix regression when using `--writable-tmpfs`
  e2e/actions/actions.go
  e2e/actions/regressions.go
  internal/pkg/runtime/engine/singularity/container_linux.go
  internal/pkg/runtime/engine/singularity/rpc/args.go
  internal/pkg/runtime/engine/singularity/rpc/client/client.go
  internal/pkg/runtime/engine/singularity/rpc/server/server_linux.go
Labels: Bug, Regression, ci:e2e

#5273 Fix CTRL-Z case
  internal/pkg/runtime/engine/singularity/monitor_linux.go
Labels: Bug

#5269 Respect available caps in set_master_privileges
  cmd/starter/c/starter.c
Labels: ci:e2e

#5303 [e2e] Pin to a 0.5.7 version of img in DockerRegistry.def
  e2e/testdata/Docker_registry.def
Labels: ci:e2e

#5308 Fix missing warning when using --writable-tmpfs with underlay.
  e2e/actions/actions.go
  e2e/actions/regressions.go
  internal/pkg/runtime/engine/singularity/prepare_linux.go
Labels: Bug, Regression

#5313 Adjust container capabilities based on latest capability available
  cmd/starter/c/include/capability.h
  cmd/starter/c/starter.c
Labels: Bug, Regression, ci:e2e

#5323 Bump github.com/blang/semver from 3.5.1 to 4.0.0
  e2e/version/version.go
  go.mod
  go.sum
  internal/pkg/plugin/module.go
Labels: dependencies

#5324 Bump github.com/buger/jsonparser to 1.0.0
  go.mod
  go.sum
Labels: dependencies

#5325 Bump github.com/spf13/cobra to 1.0.0
  e2e/plugin/testdata/cli/go.mod
  e2e/plugin/testdata/runtime_singularity/go.mod
  examples/plugins/cli-plugin/go.mod
  go.mod
  go.sum
Labels: dependencies
