Repository hpcng/singularity, pull requests merged in 2021-04, with the labels that each got.

#5907 Update opencontainers/umoci to v0.4.7 (release-3.7)
  CHANGELOG.md
  INSTALL.md
  e2e/oci/oci.go
  go.mod
  go.sum
  internal/app/singularity/oci_run_linux.go
  internal/pkg/build/sources/oci_unpack.go
  internal/pkg/runtime/engine/oci/create_linux.go
Labels: ci:e2e

#5886 Allow specified non-root users/groups to use specified --net --networks
  e2e/config/config.go
  internal/app/singularity/cache_clean_linux.go
  internal/app/singularity/cache_list_linux.go
  internal/pkg/runtime/engine/singularity/cleanup_linux.go
  internal/pkg/runtime/engine/singularity/container_linux.go
  internal/pkg/util/user/membership.go
  internal/pkg/util/user/membership_test.go
  pkg/util/singularityconf/config.go
  pkg/util/slice/slice.go
  pkg/util/slice/slice_test.go
Labels: ci:e2e

#5911 Add `--nv`, `--rocm`, `--bind` flags to build command.
  cmd/internal/cli/build.go
  cmd/internal/cli/build_linux.go
  e2e/gpu/gpu.go
  e2e/imgbuild/imgbuild.go
  e2e/internal/e2e/imagebuild.go
  internal/pkg/build/util.go
Labels: FeatureRequest, ci:e2e

#5918 Accommodate ppc64le pageSize in TestCgroups
  internal/pkg/cgroups/cgroups_linux_test.go
  internal/pkg/cgroups/example/cgroups-ppc64le.toml
Labels: Testing

#5917 Disable -race for tests on ppc64le only
  mlocal/frags/Makefile.stub
  mlocal/frags/go_common_opts.mk
  scripts/go-test.in
Labels: ci:e2e

#5919 Wrap e2e.PrepRegistry in a subtest
  e2e/suite.go
Labels: ci:e2e

#5933 fix: avoid spurious error when network not requested
  internal/pkg/runtime/engine/singularity/container_linux.go
Labels: ci:e2e

#5934 fix: avoid setfsuid return warning on some gcc versions
  cmd/starter/c/starter.c
Labels: ci:e2e

#5938 Remove TestSelfTest integration test
  cmd/singularity/cli_test.go
Labels: Testing

#5939 Do not singularity build SIF in image unit tests
  pkg/image/image_test.go
Labels: Testing

#5937 Remove obsolete integration tests (trivial cases)
  cmd/singularity/actions_test.go
  cmd/singularity/build_test.go
  cmd/singularity/docker_test.go
  cmd/singularity/env_test.go
  cmd/singularity/help_test.go
  cmd/singularity/instance_test.go
  cmd/singularity/pull_test.go
  cmd/singularity/remote_test.go
  cmd/singularity/security_test.go
  mlocal/frags/Makefile.stub
  scripts/ci-rpm-build-test
Labels: Testing, ci:e2e

#5940 Do not singularity build in ocibundle/sif tests
  go.mod
  go.sum
  pkg/ocibundle/sif/bundle_linux_test.go
Labels: Testing, ci:e2e

#5913 Add overlay command to ease the creation of ext3 writable overlay
  cmd/internal/cli/overlay.go
  cmd/internal/cli/overlay_create.go
  docs/content.go
  e2e/overlay/overlay.go
  e2e/suite.go
  internal/app/singularity/overlay_create.go
  internal/pkg/test/tool/require/require.go
Labels: ci:e2e

#5942 Remove remaining duplicate integration tests
  .circleci/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  cmd/singularity/build_test.go
  cmd/singularity/cli_test.go
  cmd/singularity/deffile_test.go
  cmd/singularity/testdata/deffile.tmpl
  cmd/singularity/testdata/runscript.sh
  cmd/singularity/testdata/seccomp-profile.json
  internal/pkg/runtime/engine/config/oci/generate/generate_test.go
  mlocal/frags/Makefile.stub
Labels: Testing, ci:e2e

#5951 oras: Work around harbor failure to accept SifConfigMediaType
  internal/pkg/client/oras/oras.go
Labels: ci:e2e

#5956 fix: respect proxy on keyserver operations
  internal/pkg/remote/endpoint/keyserver.go
Labels: Bug

#5955 Implement a copy-through ProgressCallback for silent loglevels
  internal/pkg/client/progress.go
  internal/pkg/client/progress_test.go
Labels: Bug, ci:e2e
